### Preprocessing ###
# The 0_align and 1_filter stages have been done on another machine,
# so we do only stages 2_combine, 3_window, 4_graph, and 5_histogram here.
python preprocess.py --ref_seq_file data_HEK/input/ref_seq/2DSB_R1_branch.fa --output data_HEK/output/KO_sgAB_R1_branch --dsb_pos 67 --label KO_sgAB_R1_branch --stages 2_combine 3_window 4_graph 5_histogram
python preprocess.py --ref_seq_file data_HEK/input/ref_seq/2DSB_R1_cmv.fa --output data_HEK/output/KO_sgAB_R1_cmv --dsb_pos 67 --label KO_sgAB_R1_cmv --stages 2_combine 3_window 4_graph 5_histogram
python preprocess.py --ref_seq_file data_HEK/input/ref_seq/2DSB_R1_sense.fa --output data_HEK/output/KO_sgAB_R1_sense --dsb_pos 67 --label KO_sgAB_R1_sense --stages 2_combine 3_window 4_graph 5_histogram
python preprocess.py --ref_seq_file data_HEK/input/ref_seq/2DSB_R2_branch.fa --output data_HEK/output/KO_sgAB_R2_branch --dsb_pos 46 --label KO_sgAB_R2_branch --stages 2_combine 3_window 4_graph 5_histogram
python preprocess.py --ref_seq_file data_HEK/input/ref_seq/2DSB_R2_cmv.fa --output data_HEK/output/KO_sgAB_R2_cmv --dsb_pos 46 --label KO_sgAB_R2_cmv --stages 2_combine 3_window 4_graph 5_histogram
python preprocess.py --ref_seq_file data_HEK/input/ref_seq/2DSB_R2_sense.fa --output data_HEK/output/KO_sgAB_R2_sense --dsb_pos 46 --label KO_sgAB_R2_sense --stages 2_combine 3_window 4_graph 5_histogram
python preprocess.py --ref_seq_file data_HEK/input/ref_seq/1DSB_R1_branch.fa --output data_HEK/output/KO_sgA_R1_branch --dsb_pos 67 --label KO_sgA_R1_branch --stages 2_combine 3_window 4_graph 5_histogram
python preprocess.py --ref_seq_file data_HEK/input/ref_seq/1DSB_R1_branch.fa --output data_HEK/output/KO_sgA_R1_branch_30bpDown --dsb_pos 97 --label KO_sgA_R1_branch_30bpDown --stages 2_combine 3_window 4_graph 5_histogram
python preprocess.py --ref_seq_file data_HEK/input/ref_seq/1DSB_R1_branch.fa --output data_HEK/output/KO_sgA_R1_branch_nodsb --dsb_pos 67 --label KO_sgA_R1_branch_nodsb --stages 2_combine 3_window 4_graph 5_histogram
python preprocess.py --ref_seq_file data_HEK/input/ref_seq/1DSB_R1_cmv.fa --output data_HEK/output/KO_sgA_R1_cmv --dsb_pos 67 --label KO_sgA_R1_cmv --stages 2_combine 3_window 4_graph 5_histogram
python preprocess.py --ref_seq_file data_HEK/input/ref_seq/1DSB_R1_cmv.fa --output data_HEK/output/KO_sgA_R1_cmv_30bpDown --dsb_pos 97 --label KO_sgA_R1_cmv_30bpDown --stages 2_combine 3_window 4_graph 5_histogram
python preprocess.py --ref_seq_file data_HEK/input/ref_seq/1DSB_R1_cmv.fa --output data_HEK/output/KO_sgA_R1_cmv_nodsb --dsb_pos 67 --label KO_sgA_R1_cmv_nodsb --stages 2_combine 3_window 4_graph 5_histogram
python preprocess.py --ref_seq_file data_HEK/input/ref_seq/1DSB_R1_sense.fa --output data_HEK/output/KO_sgA_R1_sense --dsb_pos 67 --label KO_sgA_R1_sense --stages 2_combine 3_window 4_graph 5_histogram
python preprocess.py --ref_seq_file data_HEK/input/ref_seq/1DSB_R1_sense.fa --output data_HEK/output/KO_sgA_R1_sense_30bpDown --dsb_pos 97 --label KO_sgA_R1_sense_30bpDown --stages 2_combine 3_window 4_graph 5_histogram
python preprocess.py --ref_seq_file data_HEK/input/ref_seq/1DSB_R1_sense.fa --output data_HEK/output/KO_sgA_R1_sense_nodsb --dsb_pos 67 --label KO_sgA_R1_sense_nodsb --stages 2_combine 3_window 4_graph 5_histogram
python preprocess.py --ref_seq_file data_HEK/input/ref_seq/1DSB_R2_branch.fa --output data_HEK/output/KO_sgB_R2_branch --dsb_pos 46 --label KO_sgB_R2_branch --stages 2_combine 3_window 4_graph 5_histogram
python preprocess.py --ref_seq_file data_HEK/input/ref_seq/1DSB_R2_branch.fa --output data_HEK/output/KO_sgB_R2_branch_30bpDown --dsb_pos 76 --label KO_sgB_R2_branch_30bpDown --stages 2_combine 3_window 4_graph 5_histogram
python preprocess.py --ref_seq_file data_HEK/input/ref_seq/1DSB_R2_branch.fa --output data_HEK/output/KO_sgB_R2_branch_nodsb --dsb_pos 46 --label KO_sgB_R2_branch_nodsb --stages 2_combine 3_window 4_graph 5_histogram
python preprocess.py --ref_seq_file data_HEK/input/ref_seq/1DSB_R2_cmv.fa --output data_HEK/output/KO_sgB_R2_cmv --dsb_pos 46 --label KO_sgB_R2_cmv --stages 2_combine 3_window 4_graph 5_histogram
python preprocess.py --ref_seq_file data_HEK/input/ref_seq/1DSB_R2_cmv.fa --output data_HEK/output/KO_sgB_R2_cmv_30bpDown --dsb_pos 76 --label KO_sgB_R2_cmv_30bpDown --stages 2_combine 3_window 4_graph 5_histogram
python preprocess.py --ref_seq_file data_HEK/input/ref_seq/1DSB_R2_cmv.fa --output data_HEK/output/KO_sgB_R2_cmv_nodsb --dsb_pos 46 --label KO_sgB_R2_cmv_nodsb --stages 2_combine 3_window 4_graph 5_histogram
python preprocess.py --ref_seq_file data_HEK/input/ref_seq/1DSB_R2_sense.fa --output data_HEK/output/KO_sgB_R2_sense --dsb_pos 46 --label KO_sgB_R2_sense --stages 2_combine 3_window 4_graph 5_histogram
python preprocess.py --ref_seq_file data_HEK/input/ref_seq/1DSB_R2_sense.fa --output data_HEK/output/KO_sgB_R2_sense_30bpDown --dsb_pos 76 --label KO_sgB_R2_sense_30bpDown --stages 2_combine 3_window 4_graph 5_histogram
python preprocess.py --ref_seq_file data_HEK/input/ref_seq/1DSB_R2_sense.fa --output data_HEK/output/KO_sgB_R2_sense_nodsb --dsb_pos 46 --label KO_sgB_R2_sense_nodsb --stages 2_combine 3_window 4_graph 5_histogram
python preprocess.py --ref_seq_file data_HEK/input/ref_seq/2DSB_R1_branch.fa --output data_HEK/output/WT_sgAB_R1_branch --dsb_pos 67 --label WT_sgAB_R1_branch --stages 2_combine 3_window 4_graph 5_histogram
python preprocess.py --ref_seq_file data_HEK/input/ref_seq/2DSB_R1_cmv.fa --output data_HEK/output/WT_sgAB_R1_cmv --dsb_pos 67 --label WT_sgAB_R1_cmv --stages 2_combine 3_window 4_graph 5_histogram
python preprocess.py --ref_seq_file data_HEK/input/ref_seq/2DSB_R1_sense.fa --output data_HEK/output/WT_sgAB_R1_sense --dsb_pos 67 --label WT_sgAB_R1_sense --stages 2_combine 3_window 4_graph 5_histogram
python preprocess.py --ref_seq_file data_HEK/input/ref_seq/2DSB_R2_branch.fa --output data_HEK/output/WT_sgAB_R2_branch --dsb_pos 46 --label WT_sgAB_R2_branch --stages 2_combine 3_window 4_graph 5_histogram
python preprocess.py --ref_seq_file data_HEK/input/ref_seq/2DSB_R2_cmv.fa --output data_HEK/output/WT_sgAB_R2_cmv --dsb_pos 46 --label WT_sgAB_R2_cmv --stages 2_combine 3_window 4_graph 5_histogram
python preprocess.py --ref_seq_file data_HEK/input/ref_seq/2DSB_R2_sense.fa --output data_HEK/output/WT_sgAB_R2_sense --dsb_pos 46 --label WT_sgAB_R2_sense --stages 2_combine 3_window 4_graph 5_histogram
python preprocess.py --ref_seq_file data_HEK/input/ref_seq/1DSB_R1_branch.fa --output data_HEK/output/WT_sgA_R1_branch --dsb_pos 67 --label WT_sgA_R1_branch --stages 2_combine 3_window 4_graph 5_histogram
python preprocess.py --ref_seq_file data_HEK/input/ref_seq/1DSB_R1_branch.fa --output data_HEK/output/WT_sgA_R1_branch_30bpDown --dsb_pos 97 --label WT_sgA_R1_branch_30bpDown --stages 2_combine 3_window 4_graph 5_histogram
python preprocess.py --ref_seq_file data_HEK/input/ref_seq/1DSB_R1_branch.fa --output data_HEK/output/WT_sgA_R1_branch_nodsb --dsb_pos 67 --label WT_sgA_R1_branch_nodsb --stages 2_combine 3_window 4_graph 5_histogram
python preprocess.py --ref_seq_file data_HEK/input/ref_seq/1DSB_R1_cmv.fa --output data_HEK/output/WT_sgA_R1_cmv --dsb_pos 67 --label WT_sgA_R1_cmv --stages 2_combine 3_window 4_graph 5_histogram
python preprocess.py --ref_seq_file data_HEK/input/ref_seq/1DSB_R1_cmv.fa --output data_HEK/output/WT_sgA_R1_cmv_30bpDown --dsb_pos 97 --label WT_sgA_R1_cmv_30bpDown --stages 2_combine 3_window 4_graph 5_histogram
python preprocess.py --ref_seq_file data_HEK/input/ref_seq/1DSB_R1_cmv.fa --output data_HEK/output/WT_sgA_R1_cmv_nodsb --dsb_pos 67 --label WT_sgA_R1_cmv_nodsb --stages 2_combine 3_window 4_graph 5_histogram
python preprocess.py --ref_seq_file data_HEK/input/ref_seq/1DSB_R1_sense.fa --output data_HEK/output/WT_sgA_R1_sense --dsb_pos 67 --label WT_sgA_R1_sense --stages 2_combine 3_window 4_graph 5_histogram
python preprocess.py --ref_seq_file data_HEK/input/ref_seq/1DSB_R1_sense.fa --output data_HEK/output/WT_sgA_R1_sense_30bpDown --dsb_pos 97 --label WT_sgA_R1_sense_30bpDown --stages 2_combine 3_window 4_graph 5_histogram
python preprocess.py --ref_seq_file data_HEK/input/ref_seq/1DSB_R1_sense.fa --output data_HEK/output/WT_sgA_R1_sense_nodsb --dsb_pos 67 --label WT_sgA_R1_sense_nodsb --stages 2_combine 3_window 4_graph 5_histogram
python preprocess.py --ref_seq_file data_HEK/input/ref_seq/1DSB_R2_branch.fa --output data_HEK/output/WT_sgB_R2_branch --dsb_pos 46 --label WT_sgB_R2_branch --stages 2_combine 3_window 4_graph 5_histogram
python preprocess.py --ref_seq_file data_HEK/input/ref_seq/1DSB_R2_branch.fa --output data_HEK/output/WT_sgB_R2_branch_30bpDown --dsb_pos 76 --label WT_sgB_R2_branch_30bpDown --stages 2_combine 3_window 4_graph 5_histogram
python preprocess.py --ref_seq_file data_HEK/input/ref_seq/1DSB_R2_branch.fa --output data_HEK/output/WT_sgB_R2_branch_nodsb --dsb_pos 46 --label WT_sgB_R2_branch_nodsb --stages 2_combine 3_window 4_graph 5_histogram
python preprocess.py --ref_seq_file data_HEK/input/ref_seq/1DSB_R2_cmv.fa --output data_HEK/output/WT_sgB_R2_cmv --dsb_pos 46 --label WT_sgB_R2_cmv --stages 2_combine 3_window 4_graph 5_histogram
python preprocess.py --ref_seq_file data_HEK/input/ref_seq/1DSB_R2_cmv.fa --output data_HEK/output/WT_sgB_R2_cmv_30bpDown --dsb_pos 76 --label WT_sgB_R2_cmv_30bpDown --stages 2_combine 3_window 4_graph 5_histogram
python preprocess.py --ref_seq_file data_HEK/input/ref_seq/1DSB_R2_cmv.fa --output data_HEK/output/WT_sgB_R2_cmv_nodsb --dsb_pos 46 --label WT_sgB_R2_cmv_nodsb --stages 2_combine 3_window 4_graph 5_histogram
python preprocess.py --ref_seq_file data_HEK/input/ref_seq/1DSB_R2_sense.fa --output data_HEK/output/WT_sgB_R2_sense --dsb_pos 46 --label WT_sgB_R2_sense --stages 2_combine 3_window 4_graph 5_histogram
python preprocess.py --ref_seq_file data_HEK/input/ref_seq/1DSB_R2_sense.fa --output data_HEK/output/WT_sgB_R2_sense_30bpDown --dsb_pos 76 --label WT_sgB_R2_sense_30bpDown --stages 2_combine 3_window 4_graph 5_histogram
python preprocess.py --ref_seq_file data_HEK/input/ref_seq/1DSB_R2_sense.fa --output data_HEK/output/WT_sgB_R2_sense_nodsb --dsb_pos 46 --label WT_sgB_R2_sense_nodsb --stages 2_combine 3_window 4_graph 5_histogram
python preprocess.py --ref_seq_file data_HEK/input/ref_seq/2DSB_R1_antisense_new.fa --output data_HEK/output/WT_sgCD_R1_antisense_new --dsb_pos 66 --label WT_sgCD_R1_antisense_new --stages 2_combine 3_window 4_graph 5_histogram
python preprocess.py --ref_seq_file data_HEK/input/ref_seq/2DSB_R1_antisense_old.fa --output data_HEK/output/WT_sgCD_R1_antisense_old --dsb_pos 50 --label WT_sgCD_R1_antisense_old --stages 2_combine 3_window 4_graph 5_histogram
python preprocess.py --ref_seq_file data_HEK/input/ref_seq/2DSB_R1_splicing_new.fa --output data_HEK/output/WT_sgCD_R1_splicing_new --dsb_pos 66 --label WT_sgCD_R1_splicing_new --stages 2_combine 3_window 4_graph 5_histogram
python preprocess.py --ref_seq_file data_HEK/input/ref_seq/2DSB_R1_splicing_old.fa --output data_HEK/output/WT_sgCD_R1_splicing_old --dsb_pos 50 --label WT_sgCD_R1_splicing_old --stages 2_combine 3_window 4_graph 5_histogram
python preprocess.py --ref_seq_file data_HEK/input/ref_seq/2DSB_R2_antisense_new.fa --output data_HEK/output/WT_sgCD_R2_antisense_new --dsb_pos 47 --label WT_sgCD_R2_antisense_new --stages 2_combine 3_window 4_graph 5_histogram
python preprocess.py --ref_seq_file data_HEK/input/ref_seq/2DSB_R2_antisense_old.fa --output data_HEK/output/WT_sgCD_R2_antisense_old --dsb_pos 47 --label WT_sgCD_R2_antisense_old --stages 2_combine 3_window 4_graph 5_histogram
python preprocess.py --ref_seq_file data_HEK/input/ref_seq/2DSB_R2_splicing_new.fa --output data_HEK/output/WT_sgCD_R2_splicing_new --dsb_pos 47 --label WT_sgCD_R2_splicing_new --stages 2_combine 3_window 4_graph 5_histogram
python preprocess.py --ref_seq_file data_HEK/input/ref_seq/2DSB_R2_splicing_old.fa --output data_HEK/output/WT_sgCD_R2_splicing_old --dsb_pos 47 --label WT_sgCD_R2_splicing_old --stages 2_combine 3_window 4_graph 5_histogram

### Get comparison data ###
python comparison.py --input data_HEK/output/KO_sgAB_R1_sense data_HEK/output/KO_sgAB_R1_branch --output data_HEK/output/KO_sgAB_R1_sense_branch
python comparison.py --input data_HEK/output/KO_sgAB_R1_sense data_HEK/output/KO_sgAB_R1_cmv --output data_HEK/output/KO_sgAB_R1_sense_cmv
python comparison.py --input data_HEK/output/KO_sgAB_R2_sense data_HEK/output/KO_sgAB_R2_branch --output data_HEK/output/KO_sgAB_R2_sense_branch
python comparison.py --input data_HEK/output/KO_sgAB_R2_sense data_HEK/output/KO_sgAB_R2_cmv --output data_HEK/output/KO_sgAB_R2_sense_cmv
python comparison.py --input data_HEK/output/KO_sgA_R1_sense data_HEK/output/KO_sgA_R1_branch --output data_HEK/output/KO_sgA_R1_sense_branch
python comparison.py --input data_HEK/output/KO_sgA_R1_sense data_HEK/output/KO_sgA_R1_cmv --output data_HEK/output/KO_sgA_R1_sense_cmv
python comparison.py --input data_HEK/output/KO_sgB_R2_sense data_HEK/output/KO_sgB_R2_branch --output data_HEK/output/KO_sgB_R2_sense_branch
python comparison.py --input data_HEK/output/KO_sgB_R2_sense data_HEK/output/KO_sgB_R2_cmv --output data_HEK/output/KO_sgB_R2_sense_cmv
python comparison.py --input data_HEK/output/WT_sgAB_R1_sense data_HEK/output/WT_sgAB_R1_branch --output data_HEK/output/WT_sgAB_R1_sense_branch
python comparison.py --input data_HEK/output/WT_sgAB_R1_sense data_HEK/output/WT_sgAB_R1_cmv --output data_HEK/output/WT_sgAB_R1_sense_cmv
python comparison.py --input data_HEK/output/WT_sgAB_R2_sense data_HEK/output/WT_sgAB_R2_branch --output data_HEK/output/WT_sgAB_R2_sense_branch
python comparison.py --input data_HEK/output/WT_sgAB_R2_sense data_HEK/output/WT_sgAB_R2_cmv --output data_HEK/output/WT_sgAB_R2_sense_cmv
python comparison.py --input data_HEK/output/WT_sgA_R1_sense data_HEK/output/WT_sgA_R1_branch --output data_HEK/output/WT_sgA_R1_sense_branch
python comparison.py --input data_HEK/output/WT_sgA_R1_sense data_HEK/output/WT_sgA_R1_cmv --output data_HEK/output/WT_sgA_R1_sense_cmv
python comparison.py --input data_HEK/output/WT_sgB_R2_sense data_HEK/output/WT_sgB_R2_branch --output data_HEK/output/WT_sgB_R2_sense_branch
python comparison.py --input data_HEK/output/WT_sgB_R2_sense data_HEK/output/WT_sgB_R2_cmv --output data_HEK/output/WT_sgB_R2_sense_cmv
python comparison.py --input data_HEK/output/WT_sgCD_R1_antisense_merged data_HEK/output/WT_sgCD_R1_splicing_merged --output data_HEK/output/WT_sgCD_R1_antisense_splicing_merged
python comparison.py --input data_HEK/output/WT_sgCD_R1_antisense_new data_HEK/output/WT_sgCD_R1_splicing_new --output data_HEK/output/WT_sgCD_R1_antisense_splicing_new
python comparison.py --input data_HEK/output/WT_sgCD_R1_antisense_old data_HEK/output/WT_sgCD_R1_splicing_old --output data_HEK/output/WT_sgCD_R1_antisense_splicing_old
python comparison.py --input data_HEK/output/WT_sgCD_R2_antisense_merged data_HEK/output/WT_sgCD_R2_splicing_merged --output data_HEK/output/WT_sgCD_R2_antisense_splicing_merged
python comparison.py --input data_HEK/output/WT_sgCD_R2_antisense_new data_HEK/output/WT_sgCD_R2_splicing_new --output data_HEK/output/WT_sgCD_R2_antisense_splicing_new
python comparison.py --input data_HEK/output/WT_sgCD_R2_antisense_old data_HEK/output/WT_sgCD_R2_splicing_old --output data_HEK/output/WT_sgCD_R2_antisense_splicing_old

### Plot individual graphs ###
python graph.py --input data_HEK/output/KO_sgAB_R1_branch --output plot_HEK/graph/individual --ext png --layout universal --width 2400 --height 1800 --range_x -12 13 --range_y -22 22 --universal_layout_y_axis_x_pos 12 --universal_layout_y_axis_y_range -19.5 20.5 --universal_layout_y_axis_insertion_max_tick 7 --universal_layout_y_axis_deletion_max_tick 17
python graph.py --input data_HEK/output/KO_sgAB_R1_cmv --output plot_HEK/graph/individual --ext png --layout universal --width 2400 --height 1800 --range_x -12 13 --range_y -22 22 --universal_layout_y_axis_x_pos 12 --universal_layout_y_axis_y_range -19.5 20.5 --universal_layout_y_axis_insertion_max_tick 7 --universal_layout_y_axis_deletion_max_tick 17
python graph.py --input data_HEK/output/KO_sgAB_R1_sense --output plot_HEK/graph/individual --ext png --layout universal --width 2400 --height 1800 --range_x -12 13 --range_y -22 22 --universal_layout_y_axis_x_pos 12 --universal_layout_y_axis_y_range -19.5 20.5 --universal_layout_x_axis_deletion_y_pos -20.5 --universal_layout_x_axis_insertion_y_pos 21.5 --universal_layout_x_axis_x_range -11.5 11.5 --universal_layout_y_axis_insertion_max_tick 7 --universal_layout_y_axis_deletion_max_tick 17
python graph.py --input data_HEK/output/KO_sgAB_R2_branch --output plot_HEK/graph/individual --ext png --layout universal --reverse_complement --width 2400 --height 1800 --range_x -12 13 --range_y -22 22 --universal_layout_y_axis_x_pos 12 --universal_layout_y_axis_y_range -19.5 20.5 --universal_layout_y_axis_insertion_max_tick 7 --universal_layout_y_axis_deletion_max_tick 17
python graph.py --input data_HEK/output/KO_sgAB_R2_cmv --output plot_HEK/graph/individual --ext png --layout universal --reverse_complement --width 2400 --height 1800 --range_x -12 13 --range_y -22 22 --universal_layout_y_axis_x_pos 12 --universal_layout_y_axis_y_range -19.5 20.5 --universal_layout_y_axis_insertion_max_tick 7 --universal_layout_y_axis_deletion_max_tick 17
python graph.py --input data_HEK/output/KO_sgAB_R2_sense --output plot_HEK/graph/individual --ext png --layout universal --reverse_complement --width 2400 --height 1800 --range_x -12 13 --range_y -22 22 --universal_layout_y_axis_x_pos 12 --universal_layout_y_axis_y_range -19.5 20.5 --universal_layout_y_axis_insertion_max_tick 7 --universal_layout_y_axis_deletion_max_tick 17
python graph.py --input data_HEK/output/KO_sgA_R1_branch --output plot_HEK/graph/individual --ext png --layout universal --width 2400 --height 1800 --range_x -12 13 --range_y -23 20 --universal_layout_y_axis_x_pos 12 --universal_layout_y_axis_y_range -20.5 18.5 --universal_layout_y_axis_insertion_max_tick 6 --universal_layout_y_axis_deletion_max_tick 19
python graph.py --input data_HEK/output/KO_sgA_R1_cmv --output plot_HEK/graph/individual --ext png --layout universal --width 2400 --height 1800 --range_x -12 13 --range_y -23 20 --universal_layout_y_axis_x_pos 12 --universal_layout_y_axis_y_range -20.5 18.5 --universal_layout_y_axis_insertion_max_tick 6 --universal_layout_y_axis_deletion_max_tick 19
python graph.py --input data_HEK/output/KO_sgA_R1_sense --output plot_HEK/graph/individual --ext png --layout universal --width 2400 --height 1800 --range_x -12 13 --range_y -23 20 --universal_layout_y_axis_x_pos 12 --universal_layout_y_axis_y_range -20.5 18.5 --universal_layout_x_axis_deletion_y_pos -21.5 --universal_layout_x_axis_insertion_y_pos 19.5 --universal_layout_x_axis_x_range -11.5 11.5 --universal_layout_y_axis_insertion_max_tick 6 --universal_layout_y_axis_deletion_max_tick 19
python graph.py --input data_HEK/output/KO_sgB_R2_branch --output plot_HEK/graph/individual --ext png --layout universal --reverse_complement --width 2400 --height 1800 --range_x -12 13 --range_y -22 16 --universal_layout_y_axis_x_pos 12 --universal_layout_y_axis_y_range -19.5 14.5 --universal_layout_y_axis_insertion_max_tick 5 --universal_layout_y_axis_deletion_max_tick 18
python graph.py --input data_HEK/output/KO_sgB_R2_cmv --output plot_HEK/graph/individual --ext png --layout universal --reverse_complement --width 2400 --height 1800 --range_x -12 13 --range_y -22 16 --universal_layout_y_axis_x_pos 12 --universal_layout_y_axis_y_range -19.5 14.5 --universal_layout_y_axis_insertion_max_tick 5 --universal_layout_y_axis_deletion_max_tick 18
python graph.py --input data_HEK/output/KO_sgB_R2_sense --output plot_HEK/graph/individual --ext png --layout universal --reverse_complement --width 2400 --height 1800 --range_x -12 13 --range_y -22 16 --universal_layout_y_axis_x_pos 12 --universal_layout_y_axis_y_range -19.5 14.5 --universal_layout_y_axis_insertion_max_tick 5 --universal_layout_y_axis_deletion_max_tick 18
python graph.py --input data_HEK/output/WT_sgAB_R1_branch --output plot_HEK/graph/individual --ext png --layout universal --width 2400 --height 1800 --range_x -12 13 --range_y -22 22 --universal_layout_y_axis_x_pos 12 --universal_layout_y_axis_y_range -19.5 20.5 --universal_layout_y_axis_insertion_max_tick 7 --universal_layout_y_axis_deletion_max_tick 17
python graph.py --input data_HEK/output/WT_sgAB_R1_cmv --output plot_HEK/graph/individual --ext png --layout universal --width 2400 --height 1800 --range_x -12 13 --range_y -22 22 --universal_layout_y_axis_x_pos 12 --universal_layout_y_axis_y_range -19.5 20.5 --universal_layout_y_axis_insertion_max_tick 7 --universal_layout_y_axis_deletion_max_tick 17
python graph.py --input data_HEK/output/WT_sgAB_R1_sense --output plot_HEK/graph/individual --ext png --layout universal --width 2400 --height 1800 --range_x -12 13 --range_y -22 22 --universal_layout_y_axis_x_pos 12 --universal_layout_y_axis_y_range -19.5 20.5 --universal_layout_x_axis_deletion_y_pos -20.5 --universal_layout_x_axis_insertion_y_pos 21.5 --universal_layout_x_axis_x_range -11.5 11.5 --universal_layout_y_axis_insertion_max_tick 7 --universal_layout_y_axis_deletion_max_tick 17
python graph.py --input data_HEK/output/WT_sgAB_R2_branch --output plot_HEK/graph/individual --ext png --layout universal --reverse_complement --width 2400 --height 1800 --range_x -12 13 --range_y -22 22 --universal_layout_y_axis_x_pos 12 --universal_layout_y_axis_y_range -19.5 20.5 --universal_layout_y_axis_insertion_max_tick 7 --universal_layout_y_axis_deletion_max_tick 17
python graph.py --input data_HEK/output/WT_sgAB_R2_cmv --output plot_HEK/graph/individual --ext png --layout universal --reverse_complement --width 2400 --height 1800 --range_x -12 13 --range_y -22 22 --universal_layout_y_axis_x_pos 12 --universal_layout_y_axis_y_range -19.5 20.5 --universal_layout_y_axis_insertion_max_tick 7 --universal_layout_y_axis_deletion_max_tick 17
python graph.py --input data_HEK/output/WT_sgAB_R2_sense --output plot_HEK/graph/individual --ext png --layout universal --reverse_complement --width 2400 --height 1800 --range_x -12 13 --range_y -22 22 --universal_layout_y_axis_x_pos 12 --universal_layout_y_axis_y_range -19.5 20.5 --universal_layout_y_axis_insertion_max_tick 7 --universal_layout_y_axis_deletion_max_tick 17
python graph.py --input data_HEK/output/WT_sgA_R1_branch --output plot_HEK/graph/individual --ext png --layout universal --width 2400 --height 1800 --range_x -12 13 --range_y -23 20 --universal_layout_y_axis_x_pos 12 --universal_layout_y_axis_y_range -20.5 18.5 --universal_layout_y_axis_insertion_max_tick 6 --universal_layout_y_axis_deletion_max_tick 19
python graph.py --input data_HEK/output/WT_sgA_R1_cmv --output plot_HEK/graph/individual --ext png --layout universal --width 2400 --height 1800 --range_x -12 13 --range_y -23 20 --universal_layout_y_axis_x_pos 12 --universal_layout_y_axis_y_range -20.5 18.5 --universal_layout_y_axis_insertion_max_tick 6 --universal_layout_y_axis_deletion_max_tick 19
python graph.py --input data_HEK/output/WT_sgA_R1_sense --output plot_HEK/graph/individual --ext png --layout universal --width 2400 --height 1800 --range_x -12 13 --range_y -23 20 --universal_layout_y_axis_x_pos 12 --universal_layout_y_axis_y_range -20.5 18.5 --universal_layout_x_axis_deletion_y_pos -21.5 --universal_layout_x_axis_insertion_y_pos 19.5 --universal_layout_x_axis_x_range -11.5 11.5 --universal_layout_y_axis_insertion_max_tick 6 --universal_layout_y_axis_deletion_max_tick 19
python graph.py --input data_HEK/output/WT_sgB_R2_branch --output plot_HEK/graph/individual --ext png --layout universal --reverse_complement --width 2400 --height 1800 --range_x -12 13 --range_y -22 16 --universal_layout_y_axis_x_pos 12 --universal_layout_y_axis_y_range -19.5 14.5 --universal_layout_y_axis_insertion_max_tick 5 --universal_layout_y_axis_deletion_max_tick 18
python graph.py --input data_HEK/output/WT_sgB_R2_cmv --output plot_HEK/graph/individual --ext png --layout universal --reverse_complement --width 2400 --height 1800 --range_x -12 13 --range_y -22 16 --universal_layout_y_axis_x_pos 12 --universal_layout_y_axis_y_range -19.5 14.5 --universal_layout_y_axis_insertion_max_tick 5 --universal_layout_y_axis_deletion_max_tick 18
python graph.py --input data_HEK/output/WT_sgB_R2_sense --output plot_HEK/graph/individual --ext png --layout universal --reverse_complement --width 2400 --height 1800 --range_x -12 13 --range_y -22 16 --universal_layout_y_axis_x_pos 12 --universal_layout_y_axis_y_range -19.5 14.5 --universal_layout_y_axis_insertion_max_tick 5 --universal_layout_y_axis_deletion_max_tick 18
python graph.py --input data_HEK/output/WT_sgCD_R1_antisense_new --output plot_HEK/graph/individual --ext png --layout universal --width 2400 --height 1800 --range_x -12 13 --range_y -22 27 --universal_layout_y_axis_x_pos 12 --universal_layout_y_axis_y_range -19.5 25.5 --universal_layout_x_axis_deletion_y_pos -20.5 --universal_layout_x_axis_insertion_y_pos 26.5 --universal_layout_x_axis_x_range -11.5 11.5 --universal_layout_y_axis_insertion_max_tick 8 --universal_layout_y_axis_deletion_max_tick 17
python graph.py --input data_HEK/output/WT_sgCD_R1_antisense_old --output plot_HEK/graph/individual --ext png --layout universal --width 2400 --height 1800 --range_x -12 13 --range_y -22 27 --universal_layout_y_axis_x_pos 12 --universal_layout_y_axis_y_range -19.5 25.5 --universal_layout_x_axis_deletion_y_pos -20.5 --universal_layout_x_axis_insertion_y_pos 26.5 --universal_layout_x_axis_x_range -11.5 11.5 --universal_layout_y_axis_insertion_max_tick 8 --universal_layout_y_axis_deletion_max_tick 17
python graph.py --input data_HEK/output/WT_sgCD_R1_splicing_new --output plot_HEK/graph/individual --ext png --layout universal --width 2400 --height 1800 --range_x -12 13 --range_y -22 27 --universal_layout_y_axis_x_pos 12 --universal_layout_y_axis_y_range -19.5 25.5 --universal_layout_y_axis_insertion_max_tick 8 --universal_layout_y_axis_deletion_max_tick 17
python graph.py --input data_HEK/output/WT_sgCD_R1_splicing_old --output plot_HEK/graph/individual --ext png --layout universal --width 2400 --height 1800 --range_x -12 13 --range_y -22 27 --universal_layout_y_axis_x_pos 12 --universal_layout_y_axis_y_range -19.5 25.5 --universal_layout_y_axis_insertion_max_tick 8 --universal_layout_y_axis_deletion_max_tick 17
python graph.py --input data_HEK/output/WT_sgCD_R2_antisense_new --output plot_HEK/graph/individual --ext png --layout universal --reverse_complement --width 2400 --height 1800 --range_x -12 13 --range_y -22 27 --universal_layout_y_axis_x_pos 12 --universal_layout_y_axis_y_range -19.5 25.5 --universal_layout_y_axis_insertion_max_tick 8 --universal_layout_y_axis_deletion_max_tick 17
python graph.py --input data_HEK/output/WT_sgCD_R2_antisense_old --output plot_HEK/graph/individual --ext png --layout universal --reverse_complement --width 2400 --height 1800 --range_x -12 13 --range_y -22 27 --universal_layout_y_axis_x_pos 12 --universal_layout_y_axis_y_range -19.5 25.5 --universal_layout_y_axis_insertion_max_tick 8 --universal_layout_y_axis_deletion_max_tick 17
python graph.py --input data_HEK/output/WT_sgCD_R2_splicing_new --output plot_HEK/graph/individual --ext png --layout universal --reverse_complement --width 2400 --height 1800 --range_x -12 13 --range_y -22 27 --universal_layout_y_axis_x_pos 12 --universal_layout_y_axis_y_range -19.5 25.5 --universal_layout_y_axis_insertion_max_tick 8 --universal_layout_y_axis_deletion_max_tick 17
python graph.py --input data_HEK/output/WT_sgCD_R2_splicing_old --output plot_HEK/graph/individual --ext png --layout universal --reverse_complement --width 2400 --height 1800 --range_x -12 13 --range_y -22 27 --universal_layout_y_axis_x_pos 12 --universal_layout_y_axis_y_range -19.5 25.5 --universal_layout_y_axis_insertion_max_tick 8 --universal_layout_y_axis_deletion_max_tick 17
python graph.py --input data_HEK/output/KO_sgAB_R1_sense_branch --output plot_HEK/graph/comparison --ext png --layout universal --width 2400 --height 1800 --range_x -12 13 --range_y -22 22 --universal_layout_y_axis_x_pos 12 --universal_layout_y_axis_y_range -19.5 20.5 --universal_layout_y_axis_insertion_max_tick 7 --universal_layout_y_axis_deletion_max_tick 17

### Plot comparison graphs ###
python graph.py --input data_HEK/output/KO_sgAB_R1_sense_cmv --output plot_HEK/graph/comparison --ext png --layout universal --width 2400 --height 1800 --range_x -12 13 --range_y -22 22 --universal_layout_y_axis_x_pos 12 --universal_layout_y_axis_y_range -19.5 20.5 --universal_layout_y_axis_insertion_max_tick 7 --universal_layout_y_axis_deletion_max_tick 17
python graph.py --input data_HEK/output/KO_sgAB_R2_sense_branch --output plot_HEK/graph/comparison --ext png --layout universal --reverse_complement --width 2400 --height 1800 --range_x -12 13 --range_y -22 22 --universal_layout_y_axis_x_pos 12 --universal_layout_y_axis_y_range -19.5 20.5 --universal_layout_y_axis_insertion_max_tick 7 --universal_layout_y_axis_deletion_max_tick 17
python graph.py --input data_HEK/output/KO_sgAB_R2_sense_cmv --output plot_HEK/graph/comparison --ext png --layout universal --reverse_complement --width 2400 --height 1800 --range_x -12 13 --range_y -22 22 --universal_layout_y_axis_x_pos 12 --universal_layout_y_axis_y_range -19.5 20.5 --universal_layout_y_axis_insertion_max_tick 7 --universal_layout_y_axis_deletion_max_tick 17
python graph.py --input data_HEK/output/KO_sgA_R1_sense_branch --output plot_HEK/graph/comparison --ext png --layout universal --width 2400 --height 1800 --range_x -12 13 --range_y -23 20 --universal_layout_y_axis_x_pos 12 --universal_layout_y_axis_y_range -20.5 18.5 --universal_layout_y_axis_insertion_max_tick 6 --universal_layout_y_axis_deletion_max_tick 19
python graph.py --input data_HEK/output/KO_sgA_R1_sense_cmv --output plot_HEK/graph/comparison --ext png --layout universal --width 2400 --height 1800 --range_x -12 13 --range_y -23 20 --universal_layout_y_axis_x_pos 12 --universal_layout_y_axis_y_range -20.5 18.5 --universal_layout_y_axis_insertion_max_tick 6 --universal_layout_y_axis_deletion_max_tick 19
python graph.py --input data_HEK/output/KO_sgB_R2_sense_branch --output plot_HEK/graph/comparison --ext png --layout universal --reverse_complement --width 2400 --height 1800 --range_x -12 13 --range_y -22 16 --universal_layout_y_axis_x_pos 12 --universal_layout_y_axis_y_range -19.5 14.5 --universal_layout_y_axis_insertion_max_tick 5 --universal_layout_y_axis_deletion_max_tick 18
python graph.py --input data_HEK/output/KO_sgB_R2_sense_cmv --output plot_HEK/graph/comparison --ext png --layout universal --reverse_complement --width 2400 --height 1800 --range_x -12 13 --range_y -22 16 --universal_layout_y_axis_x_pos 12 --universal_layout_y_axis_y_range -19.5 14.5 --universal_layout_y_axis_insertion_max_tick 5 --universal_layout_y_axis_deletion_max_tick 18
python graph.py --input data_HEK/output/WT_sgAB_R1_sense_branch --output plot_HEK/graph/comparison --ext png --layout universal --width 2400 --height 1800 --range_x -12 13 --range_y -22 22 --universal_layout_y_axis_x_pos 12 --universal_layout_y_axis_y_range -19.5 20.5 --universal_layout_y_axis_insertion_max_tick 7 --universal_layout_y_axis_deletion_max_tick 17
python graph.py --input data_HEK/output/WT_sgAB_R1_sense_cmv --output plot_HEK/graph/comparison --ext png --layout universal --width 2400 --height 1800 --range_x -12 13 --range_y -22 22 --universal_layout_y_axis_x_pos 12 --universal_layout_y_axis_y_range -19.5 20.5 --universal_layout_y_axis_insertion_max_tick 7 --universal_layout_y_axis_deletion_max_tick 17
python graph.py --input data_HEK/output/WT_sgAB_R2_sense_branch --output plot_HEK/graph/comparison --ext png --layout universal --reverse_complement --width 2400 --height 1800 --range_x -12 13 --range_y -22 22 --universal_layout_y_axis_x_pos 12 --universal_layout_y_axis_y_range -19.5 20.5 --universal_layout_y_axis_insertion_max_tick 7 --universal_layout_y_axis_deletion_max_tick 17
python graph.py --input data_HEK/output/WT_sgAB_R2_sense_cmv --output plot_HEK/graph/comparison --ext png --layout universal --reverse_complement --width 2400 --height 1800 --range_x -12 13 --range_y -22 22 --universal_layout_y_axis_x_pos 12 --universal_layout_y_axis_y_range -19.5 20.5 --universal_layout_y_axis_insertion_max_tick 7 --universal_layout_y_axis_deletion_max_tick 17
python graph.py --input data_HEK/output/WT_sgA_R1_sense_branch --output plot_HEK/graph/comparison --ext png --layout universal --width 2400 --height 1800 --range_x -12 13 --range_y -23 20 --universal_layout_y_axis_x_pos 12 --universal_layout_y_axis_y_range -20.5 18.5 --universal_layout_y_axis_insertion_max_tick 6 --universal_layout_y_axis_deletion_max_tick 19
python graph.py --input data_HEK/output/WT_sgA_R1_sense_cmv --output plot_HEK/graph/comparison --ext png --layout universal --width 2400 --height 1800 --range_x -12 13 --range_y -23 20 --universal_layout_y_axis_x_pos 12 --universal_layout_y_axis_y_range -20.5 18.5 --universal_layout_y_axis_insertion_max_tick 6 --universal_layout_y_axis_deletion_max_tick 19
python graph.py --input data_HEK/output/WT_sgB_R2_sense_branch --output plot_HEK/graph/comparison --ext png --layout universal --reverse_complement --width 2400 --height 1800 --range_x -12 13 --range_y -22 16 --universal_layout_y_axis_x_pos 12 --universal_layout_y_axis_y_range -19.5 14.5 --universal_layout_y_axis_insertion_max_tick 5 --universal_layout_y_axis_deletion_max_tick 18
python graph.py --input data_HEK/output/WT_sgB_R2_sense_cmv --output plot_HEK/graph/comparison --ext png --layout universal --reverse_complement --width 2400 --height 1800 --range_x -12 13 --range_y -22 16 --universal_layout_y_axis_x_pos 12 --universal_layout_y_axis_y_range -19.5 14.5 --universal_layout_y_axis_insertion_max_tick 5 --universal_layout_y_axis_deletion_max_tick 18
python graph.py --input data_HEK/output/WT_sgCD_R1_antisense_splicing_merged --output plot_HEK/graph/comparison --ext png --layout universal --width 2400 --height 1800 --range_x -12 13 --range_y -22 27 --universal_layout_y_axis_x_pos 12 --universal_layout_y_axis_y_range -19.5 25.5 --universal_layout_y_axis_insertion_max_tick 8 --universal_layout_y_axis_deletion_max_tick 17
python graph.py --input data_HEK/output/WT_sgCD_R1_antisense_splicing_new --output plot_HEK/graph/comparison --ext png --layout universal --width 2400 --height 1800 --range_x -12 13 --range_y -22 27 --universal_layout_y_axis_x_pos 12 --universal_layout_y_axis_y_range -19.5 25.5 --universal_layout_y_axis_insertion_max_tick 8 --universal_layout_y_axis_deletion_max_tick 17
python graph.py --input data_HEK/output/WT_sgCD_R1_antisense_splicing_old --output plot_HEK/graph/comparison --ext png --layout universal --width 2400 --height 1800 --range_x -12 13 --range_y -22 27 --universal_layout_y_axis_x_pos 12 --universal_layout_y_axis_y_range -19.5 25.5 --universal_layout_y_axis_insertion_max_tick 8 --universal_layout_y_axis_deletion_max_tick 17
python graph.py --input data_HEK/output/WT_sgCD_R2_antisense_splicing_merged --output plot_HEK/graph/comparison --ext png --layout universal --reverse_complement --width 2400 --height 1800 --range_x -12 13 --range_y -22 27 --universal_layout_y_axis_x_pos 12 --universal_layout_y_axis_y_range -19.5 25.5 --universal_layout_y_axis_insertion_max_tick 8 --universal_layout_y_axis_deletion_max_tick 17
python graph.py --input data_HEK/output/WT_sgCD_R2_antisense_splicing_new --output plot_HEK/graph/comparison --ext png --layout universal --reverse_complement --width 2400 --height 1800 --range_x -12 13 --range_y -22 27 --universal_layout_y_axis_x_pos 12 --universal_layout_y_axis_y_range -19.5 25.5 --universal_layout_y_axis_insertion_max_tick 8 --universal_layout_y_axis_deletion_max_tick 17
python graph.py --input data_HEK/output/WT_sgCD_R2_antisense_splicing_old --output plot_HEK/graph/comparison --ext png --layout universal --reverse_complement --width 2400 --height 1800 --range_x -12 13 --range_y -22 27 --universal_layout_y_axis_x_pos 12 --universal_layout_y_axis_y_range -19.5 25.5 --universal_layout_y_axis_insertion_max_tick 8 --universal_layout_y_axis_deletion_max_tick 17

### Plot histograms ###
python histogram.py --input data_HEK/output/KO_sgAB_R1_branch --output plot_HEK/histogram/KO_sgAB_R1_branch_deletion.png --reverse_pos --label_type relative --variation_type deletion
python histogram.py --input data_HEK/output/KO_sgAB_R1_branch --output plot_HEK/histogram/KO_sgAB_R1_branch_insertion.png --reverse_pos --label_type relative --variation_type insertion
python histogram.py --input data_HEK/output/KO_sgAB_R1_branch --output plot_HEK/histogram/KO_sgAB_R1_branch_substitution.png --reverse_pos --label_type relative --variation_type substitution
python histogram.py --input data_HEK/output/KO_sgAB_R1_cmv --output plot_HEK/histogram/KO_sgAB_R1_cmv_deletion.png --reverse_pos --label_type relative --variation_type deletion
python histogram.py --input data_HEK/output/KO_sgAB_R1_cmv --output plot_HEK/histogram/KO_sgAB_R1_cmv_insertion.png --reverse_pos --label_type relative --variation_type insertion
python histogram.py --input data_HEK/output/KO_sgAB_R1_cmv --output plot_HEK/histogram/KO_sgAB_R1_cmv_substitution.png --reverse_pos --label_type relative --variation_type substitution
python histogram.py --input data_HEK/output/KO_sgAB_R1_sense --output plot_HEK/histogram/KO_sgAB_R1_sense_deletion.png --reverse_pos --label_type relative --variation_type deletion
python histogram.py --input data_HEK/output/KO_sgAB_R1_sense --output plot_HEK/histogram/KO_sgAB_R1_sense_insertion.png --reverse_pos --label_type relative --variation_type insertion
python histogram.py --input data_HEK/output/KO_sgAB_R1_sense --output plot_HEK/histogram/KO_sgAB_R1_sense_substitution.png --reverse_pos --label_type relative --variation_type substitution
python histogram.py --input data_HEK/output/KO_sgAB_R2_branch --output plot_HEK/histogram/KO_sgAB_R2_branch_deletion.png  --label_type relative --variation_type deletion
python histogram.py --input data_HEK/output/KO_sgAB_R2_branch --output plot_HEK/histogram/KO_sgAB_R2_branch_insertion.png  --label_type relative --variation_type insertion
python histogram.py --input data_HEK/output/KO_sgAB_R2_branch --output plot_HEK/histogram/KO_sgAB_R2_branch_substitution.png  --label_type relative --variation_type substitution
python histogram.py --input data_HEK/output/KO_sgAB_R2_cmv --output plot_HEK/histogram/KO_sgAB_R2_cmv_deletion.png  --label_type relative --variation_type deletion
python histogram.py --input data_HEK/output/KO_sgAB_R2_cmv --output plot_HEK/histogram/KO_sgAB_R2_cmv_insertion.png  --label_type relative --variation_type insertion
python histogram.py --input data_HEK/output/KO_sgAB_R2_cmv --output plot_HEK/histogram/KO_sgAB_R2_cmv_substitution.png  --label_type relative --variation_type substitution
python histogram.py --input data_HEK/output/KO_sgAB_R2_sense --output plot_HEK/histogram/KO_sgAB_R2_sense_deletion.png  --label_type relative --variation_type deletion
python histogram.py --input data_HEK/output/KO_sgAB_R2_sense --output plot_HEK/histogram/KO_sgAB_R2_sense_insertion.png  --label_type relative --variation_type insertion
python histogram.py --input data_HEK/output/KO_sgAB_R2_sense --output plot_HEK/histogram/KO_sgAB_R2_sense_substitution.png  --label_type relative --variation_type substitution
python histogram.py --input data_HEK/output/KO_sgA_R1_branch_30bpDown --output plot_HEK/histogram/KO_sgA_R1_branch_30bpDown_deletion.png --reverse_pos --label_type absolute --variation_type deletion
python histogram.py --input data_HEK/output/KO_sgA_R1_branch_30bpDown --output plot_HEK/histogram/KO_sgA_R1_branch_30bpDown_insertion.png --reverse_pos --label_type absolute --variation_type insertion
python histogram.py --input data_HEK/output/KO_sgA_R1_branch_30bpDown --output plot_HEK/histogram/KO_sgA_R1_branch_30bpDown_substitution.png --reverse_pos --label_type absolute --variation_type substitution
python histogram.py --input data_HEK/output/KO_sgA_R1_branch --output plot_HEK/histogram/KO_sgA_R1_branch_deletion.png --reverse_pos --label_type relative --variation_type deletion
python histogram.py --input data_HEK/output/KO_sgA_R1_branch --output plot_HEK/histogram/KO_sgA_R1_branch_insertion.png --reverse_pos --label_type relative --variation_type insertion
python histogram.py --input data_HEK/output/KO_sgA_R1_branch_noDSB --output plot_HEK/histogram/KO_sgA_R1_branch_noDSB_deletion.png --reverse_pos --label_type relative --variation_type deletion
python histogram.py --input data_HEK/output/KO_sgA_R1_branch_noDSB --output plot_HEK/histogram/KO_sgA_R1_branch_noDSB_insertion.png --reverse_pos --label_type relative --variation_type insertion
python histogram.py --input data_HEK/output/KO_sgA_R1_branch_noDSB --output plot_HEK/histogram/KO_sgA_R1_branch_noDSB_substitution.png --reverse_pos --label_type relative --variation_type substitution
python histogram.py --input data_HEK/output/KO_sgA_R1_branch --output plot_HEK/histogram/KO_sgA_R1_branch_substitution.png --reverse_pos --label_type relative --variation_type substitution
python histogram.py --input data_HEK/output/KO_sgA_R1_cmv_30bpDown --output plot_HEK/histogram/KO_sgA_R1_cmv_30bpDown_deletion.png --reverse_pos --label_type absolute --variation_type deletion
python histogram.py --input data_HEK/output/KO_sgA_R1_cmv_30bpDown --output plot_HEK/histogram/KO_sgA_R1_cmv_30bpDown_insertion.png --reverse_pos --label_type absolute --variation_type insertion
python histogram.py --input data_HEK/output/KO_sgA_R1_cmv_30bpDown --output plot_HEK/histogram/KO_sgA_R1_cmv_30bpDown_substitution.png --reverse_pos --label_type absolute --variation_type substitution
python histogram.py --input data_HEK/output/KO_sgA_R1_cmv --output plot_HEK/histogram/KO_sgA_R1_cmv_deletion.png --reverse_pos --label_type relative --variation_type deletion
python histogram.py --input data_HEK/output/KO_sgA_R1_cmv --output plot_HEK/histogram/KO_sgA_R1_cmv_insertion.png --reverse_pos --label_type relative --variation_type insertion
python histogram.py --input data_HEK/output/KO_sgA_R1_cmv_noDSB --output plot_HEK/histogram/KO_sgA_R1_cmv_noDSB_deletion.png --reverse_pos --label_type relative --variation_type deletion
python histogram.py --input data_HEK/output/KO_sgA_R1_cmv_noDSB --output plot_HEK/histogram/KO_sgA_R1_cmv_noDSB_insertion.png --reverse_pos --label_type relative --variation_type insertion
python histogram.py --input data_HEK/output/KO_sgA_R1_cmv_noDSB --output plot_HEK/histogram/KO_sgA_R1_cmv_noDSB_substitution.png --reverse_pos --label_type relative --variation_type substitution
python histogram.py --input data_HEK/output/KO_sgA_R1_cmv --output plot_HEK/histogram/KO_sgA_R1_cmv_substitution.png --reverse_pos --label_type relative --variation_type substitution
python histogram.py --input data_HEK/output/KO_sgA_R1_sense_30bpDown --output plot_HEK/histogram/KO_sgA_R1_sense_30bpDown_deletion.png --reverse_pos --label_type absolute --variation_type deletion
python histogram.py --input data_HEK/output/KO_sgA_R1_sense_30bpDown --output plot_HEK/histogram/KO_sgA_R1_sense_30bpDown_insertion.png --reverse_pos --label_type absolute --variation_type insertion
python histogram.py --input data_HEK/output/KO_sgA_R1_sense_30bpDown --output plot_HEK/histogram/KO_sgA_R1_sense_30bpDown_substitution.png --reverse_pos --label_type absolute --variation_type substitution
python histogram.py --input data_HEK/output/KO_sgA_R1_sense --output plot_HEK/histogram/KO_sgA_R1_sense_deletion.png --reverse_pos --label_type relative --variation_type deletion
python histogram.py --input data_HEK/output/KO_sgA_R1_sense --output plot_HEK/histogram/KO_sgA_R1_sense_insertion.png --reverse_pos --label_type relative --variation_type insertion
python histogram.py --input data_HEK/output/KO_sgA_R1_sense_noDSB --output plot_HEK/histogram/KO_sgA_R1_sense_noDSB_deletion.png --reverse_pos --label_type relative --variation_type deletion
python histogram.py --input data_HEK/output/KO_sgA_R1_sense_noDSB --output plot_HEK/histogram/KO_sgA_R1_sense_noDSB_insertion.png --reverse_pos --label_type relative --variation_type insertion
python histogram.py --input data_HEK/output/KO_sgA_R1_sense_noDSB --output plot_HEK/histogram/KO_sgA_R1_sense_noDSB_substitution.png --reverse_pos --label_type relative --variation_type substitution
python histogram.py --input data_HEK/output/KO_sgA_R1_sense --output plot_HEK/histogram/KO_sgA_R1_sense_substitution.png --reverse_pos --label_type relative --variation_type substitution
python histogram.py --input data_HEK/output/KO_sgB_R2_branch_30bpDown --output plot_HEK/histogram/KO_sgB_R2_branch_30bpDown_deletion.png  --label_type absolute --variation_type deletion
python histogram.py --input data_HEK/output/KO_sgB_R2_branch_30bpDown --output plot_HEK/histogram/KO_sgB_R2_branch_30bpDown_insertion.png  --label_type absolute --variation_type insertion
python histogram.py --input data_HEK/output/KO_sgB_R2_branch_30bpDown --output plot_HEK/histogram/KO_sgB_R2_branch_30bpDown_substitution.png  --label_type absolute --variation_type substitution
python histogram.py --input data_HEK/output/KO_sgB_R2_branch --output plot_HEK/histogram/KO_sgB_R2_branch_deletion.png  --label_type relative --variation_type deletion
python histogram.py --input data_HEK/output/KO_sgB_R2_branch --output plot_HEK/histogram/KO_sgB_R2_branch_insertion.png  --label_type relative --variation_type insertion
python histogram.py --input data_HEK/output/KO_sgB_R2_branch_noDSB --output plot_HEK/histogram/KO_sgB_R2_branch_noDSB_deletion.png  --label_type relative --variation_type deletion
python histogram.py --input data_HEK/output/KO_sgB_R2_branch_noDSB --output plot_HEK/histogram/KO_sgB_R2_branch_noDSB_insertion.png  --label_type relative --variation_type insertion
python histogram.py --input data_HEK/output/KO_sgB_R2_branch_noDSB --output plot_HEK/histogram/KO_sgB_R2_branch_noDSB_substitution.png  --label_type relative --variation_type substitution
python histogram.py --input data_HEK/output/KO_sgB_R2_branch --output plot_HEK/histogram/KO_sgB_R2_branch_substitution.png  --label_type relative --variation_type substitution
python histogram.py --input data_HEK/output/KO_sgB_R2_cmv_30bpDown --output plot_HEK/histogram/KO_sgB_R2_cmv_30bpDown_deletion.png  --label_type absolute --variation_type deletion
python histogram.py --input data_HEK/output/KO_sgB_R2_cmv_30bpDown --output plot_HEK/histogram/KO_sgB_R2_cmv_30bpDown_insertion.png  --label_type absolute --variation_type insertion
python histogram.py --input data_HEK/output/KO_sgB_R2_cmv_30bpDown --output plot_HEK/histogram/KO_sgB_R2_cmv_30bpDown_substitution.png  --label_type absolute --variation_type substitution
python histogram.py --input data_HEK/output/KO_sgB_R2_cmv --output plot_HEK/histogram/KO_sgB_R2_cmv_deletion.png  --label_type relative --variation_type deletion
python histogram.py --input data_HEK/output/KO_sgB_R2_cmv --output plot_HEK/histogram/KO_sgB_R2_cmv_insertion.png  --label_type relative --variation_type insertion
python histogram.py --input data_HEK/output/KO_sgB_R2_cmv_noDSB --output plot_HEK/histogram/KO_sgB_R2_cmv_noDSB_deletion.png  --label_type relative --variation_type deletion
python histogram.py --input data_HEK/output/KO_sgB_R2_cmv_noDSB --output plot_HEK/histogram/KO_sgB_R2_cmv_noDSB_insertion.png  --label_type relative --variation_type insertion
python histogram.py --input data_HEK/output/KO_sgB_R2_cmv_noDSB --output plot_HEK/histogram/KO_sgB_R2_cmv_noDSB_substitution.png  --label_type relative --variation_type substitution
python histogram.py --input data_HEK/output/KO_sgB_R2_cmv --output plot_HEK/histogram/KO_sgB_R2_cmv_substitution.png  --label_type relative --variation_type substitution
python histogram.py --input data_HEK/output/KO_sgB_R2_sense_30bpDown --output plot_HEK/histogram/KO_sgB_R2_sense_30bpDown_deletion.png  --label_type absolute --variation_type deletion
python histogram.py --input data_HEK/output/KO_sgB_R2_sense_30bpDown --output plot_HEK/histogram/KO_sgB_R2_sense_30bpDown_insertion.png  --label_type absolute --variation_type insertion
python histogram.py --input data_HEK/output/KO_sgB_R2_sense_30bpDown --output plot_HEK/histogram/KO_sgB_R2_sense_30bpDown_substitution.png  --label_type absolute --variation_type substitution
python histogram.py --input data_HEK/output/KO_sgB_R2_sense --output plot_HEK/histogram/KO_sgB_R2_sense_deletion.png  --label_type relative --variation_type deletion
python histogram.py --input data_HEK/output/KO_sgB_R2_sense --output plot_HEK/histogram/KO_sgB_R2_sense_insertion.png  --label_type relative --variation_type insertion
python histogram.py --input data_HEK/output/KO_sgB_R2_sense_noDSB --output plot_HEK/histogram/KO_sgB_R2_sense_noDSB_deletion.png  --label_type relative --variation_type deletion
python histogram.py --input data_HEK/output/KO_sgB_R2_sense_noDSB --output plot_HEK/histogram/KO_sgB_R2_sense_noDSB_insertion.png  --label_type relative --variation_type insertion
python histogram.py --input data_HEK/output/KO_sgB_R2_sense_noDSB --output plot_HEK/histogram/KO_sgB_R2_sense_noDSB_substitution.png  --label_type relative --variation_type substitution
python histogram.py --input data_HEK/output/KO_sgB_R2_sense --output plot_HEK/histogram/KO_sgB_R2_sense_substitution.png  --label_type relative --variation_type substitution
python histogram.py --input data_HEK/output/WT_sgAB_R1_branch --output plot_HEK/histogram/WT_sgAB_R1_branch_deletion.png --reverse_pos --label_type relative --variation_type deletion
python histogram.py --input data_HEK/output/WT_sgAB_R1_branch --output plot_HEK/histogram/WT_sgAB_R1_branch_insertion.png --reverse_pos --label_type relative --variation_type insertion
python histogram.py --input data_HEK/output/WT_sgAB_R1_branch --output plot_HEK/histogram/WT_sgAB_R1_branch_substitution.png --reverse_pos --label_type relative --variation_type substitution
python histogram.py --input data_HEK/output/WT_sgAB_R1_cmv --output plot_HEK/histogram/WT_sgAB_R1_cmv_deletion.png --reverse_pos --label_type relative --variation_type deletion
python histogram.py --input data_HEK/output/WT_sgAB_R1_cmv --output plot_HEK/histogram/WT_sgAB_R1_cmv_insertion.png --reverse_pos --label_type relative --variation_type insertion
python histogram.py --input data_HEK/output/WT_sgAB_R1_cmv --output plot_HEK/histogram/WT_sgAB_R1_cmv_substitution.png --reverse_pos --label_type relative --variation_type substitution
python histogram.py --input data_HEK/output/WT_sgAB_R1_sense --output plot_HEK/histogram/WT_sgAB_R1_sense_deletion.png --reverse_pos --label_type relative --variation_type deletion
python histogram.py --input data_HEK/output/WT_sgAB_R1_sense --output plot_HEK/histogram/WT_sgAB_R1_sense_insertion.png --reverse_pos --label_type relative --variation_type insertion
python histogram.py --input data_HEK/output/WT_sgAB_R1_sense --output plot_HEK/histogram/WT_sgAB_R1_sense_substitution.png --reverse_pos --label_type relative --variation_type substitution
python histogram.py --input data_HEK/output/WT_sgAB_R2_branch --output plot_HEK/histogram/WT_sgAB_R2_branch_deletion.png  --label_type relative --variation_type deletion
python histogram.py --input data_HEK/output/WT_sgAB_R2_branch --output plot_HEK/histogram/WT_sgAB_R2_branch_insertion.png  --label_type relative --variation_type insertion
python histogram.py --input data_HEK/output/WT_sgAB_R2_branch --output plot_HEK/histogram/WT_sgAB_R2_branch_substitution.png  --label_type relative --variation_type substitution
python histogram.py --input data_HEK/output/WT_sgAB_R2_cmv --output plot_HEK/histogram/WT_sgAB_R2_cmv_deletion.png  --label_type relative --variation_type deletion
python histogram.py --input data_HEK/output/WT_sgAB_R2_cmv --output plot_HEK/histogram/WT_sgAB_R2_cmv_insertion.png  --label_type relative --variation_type insertion
python histogram.py --input data_HEK/output/WT_sgAB_R2_cmv --output plot_HEK/histogram/WT_sgAB_R2_cmv_substitution.png  --label_type relative --variation_type substitution
python histogram.py --input data_HEK/output/WT_sgAB_R2_sense --output plot_HEK/histogram/WT_sgAB_R2_sense_deletion.png  --label_type relative --variation_type deletion
python histogram.py --input data_HEK/output/WT_sgAB_R2_sense --output plot_HEK/histogram/WT_sgAB_R2_sense_insertion.png  --label_type relative --variation_type insertion
python histogram.py --input data_HEK/output/WT_sgAB_R2_sense --output plot_HEK/histogram/WT_sgAB_R2_sense_substitution.png  --label_type relative --variation_type substitution
python histogram.py --input data_HEK/output/WT_sgA_R1_branch_30bpDown --output plot_HEK/histogram/WT_sgA_R1_branch_30bpDown_deletion.png --reverse_pos --label_type absolute --variation_type deletion
python histogram.py --input data_HEK/output/WT_sgA_R1_branch_30bpDown --output plot_HEK/histogram/WT_sgA_R1_branch_30bpDown_insertion.png --reverse_pos --label_type absolute --variation_type insertion
python histogram.py --input data_HEK/output/WT_sgA_R1_branch_30bpDown --output plot_HEK/histogram/WT_sgA_R1_branch_30bpDown_substitution.png --reverse_pos --label_type absolute --variation_type substitution
python histogram.py --input data_HEK/output/WT_sgA_R1_branch --output plot_HEK/histogram/WT_sgA_R1_branch_deletion.png --reverse_pos --label_type relative --variation_type deletion
python histogram.py --input data_HEK/output/WT_sgA_R1_branch --output plot_HEK/histogram/WT_sgA_R1_branch_insertion.png --reverse_pos --label_type relative --variation_type insertion
python histogram.py --input data_HEK/output/WT_sgA_R1_branch_noDSB --output plot_HEK/histogram/WT_sgA_R1_branch_noDSB_deletion.png --reverse_pos --label_type relative --variation_type deletion
python histogram.py --input data_HEK/output/WT_sgA_R1_branch_noDSB --output plot_HEK/histogram/WT_sgA_R1_branch_noDSB_insertion.png --reverse_pos --label_type relative --variation_type insertion
python histogram.py --input data_HEK/output/WT_sgA_R1_branch_noDSB --output plot_HEK/histogram/WT_sgA_R1_branch_noDSB_substitution.png --reverse_pos --label_type relative --variation_type substitution
python histogram.py --input data_HEK/output/WT_sgA_R1_branch --output plot_HEK/histogram/WT_sgA_R1_branch_substitution.png --reverse_pos --label_type relative --variation_type substitution
python histogram.py --input data_HEK/output/WT_sgA_R1_cmv_30bpDown --output plot_HEK/histogram/WT_sgA_R1_cmv_30bpDown_deletion.png --reverse_pos --label_type absolute --variation_type deletion
python histogram.py --input data_HEK/output/WT_sgA_R1_cmv_30bpDown --output plot_HEK/histogram/WT_sgA_R1_cmv_30bpDown_insertion.png --reverse_pos --label_type absolute --variation_type insertion
python histogram.py --input data_HEK/output/WT_sgA_R1_cmv_30bpDown --output plot_HEK/histogram/WT_sgA_R1_cmv_30bpDown_substitution.png --reverse_pos --label_type absolute --variation_type substitution
python histogram.py --input data_HEK/output/WT_sgA_R1_cmv --output plot_HEK/histogram/WT_sgA_R1_cmv_deletion.png --reverse_pos --label_type relative --variation_type deletion
python histogram.py --input data_HEK/output/WT_sgA_R1_cmv --output plot_HEK/histogram/WT_sgA_R1_cmv_insertion.png --reverse_pos --label_type relative --variation_type insertion
python histogram.py --input data_HEK/output/WT_sgA_R1_cmv_noDSB --output plot_HEK/histogram/WT_sgA_R1_cmv_noDSB_deletion.png --reverse_pos --label_type relative --variation_type deletion
python histogram.py --input data_HEK/output/WT_sgA_R1_cmv_noDSB --output plot_HEK/histogram/WT_sgA_R1_cmv_noDSB_insertion.png --reverse_pos --label_type relative --variation_type insertion
python histogram.py --input data_HEK/output/WT_sgA_R1_cmv_noDSB --output plot_HEK/histogram/WT_sgA_R1_cmv_noDSB_substitution.png --reverse_pos --label_type relative --variation_type substitution
python histogram.py --input data_HEK/output/WT_sgA_R1_cmv --output plot_HEK/histogram/WT_sgA_R1_cmv_substitution.png --reverse_pos --label_type relative --variation_type substitution
python histogram.py --input data_HEK/output/WT_sgA_R1_sense_30bpDown --output plot_HEK/histogram/WT_sgA_R1_sense_30bpDown_deletion.png --reverse_pos --label_type absolute --variation_type deletion
python histogram.py --input data_HEK/output/WT_sgA_R1_sense_30bpDown --output plot_HEK/histogram/WT_sgA_R1_sense_30bpDown_insertion.png --reverse_pos --label_type absolute --variation_type insertion
python histogram.py --input data_HEK/output/WT_sgA_R1_sense_30bpDown --output plot_HEK/histogram/WT_sgA_R1_sense_30bpDown_substitution.png --reverse_pos --label_type absolute --variation_type substitution
python histogram.py --input data_HEK/output/WT_sgA_R1_sense --output plot_HEK/histogram/WT_sgA_R1_sense_deletion.png --reverse_pos --label_type relative --variation_type deletion
python histogram.py --input data_HEK/output/WT_sgA_R1_sense --output plot_HEK/histogram/WT_sgA_R1_sense_insertion.png --reverse_pos --label_type relative --variation_type insertion
python histogram.py --input data_HEK/output/WT_sgA_R1_sense_noDSB --output plot_HEK/histogram/WT_sgA_R1_sense_noDSB_deletion.png --reverse_pos --label_type relative --variation_type deletion
python histogram.py --input data_HEK/output/WT_sgA_R1_sense_noDSB --output plot_HEK/histogram/WT_sgA_R1_sense_noDSB_insertion.png --reverse_pos --label_type relative --variation_type insertion
python histogram.py --input data_HEK/output/WT_sgA_R1_sense_noDSB --output plot_HEK/histogram/WT_sgA_R1_sense_noDSB_substitution.png --reverse_pos --label_type relative --variation_type substitution
python histogram.py --input data_HEK/output/WT_sgA_R1_sense --output plot_HEK/histogram/WT_sgA_R1_sense_substitution.png --reverse_pos --label_type relative --variation_type substitution
python histogram.py --input data_HEK/output/WT_sgB_R2_branch_30bpDown --output plot_HEK/histogram/WT_sgB_R2_branch_30bpDown_deletion.png  --label_type absolute --variation_type deletion
python histogram.py --input data_HEK/output/WT_sgB_R2_branch_30bpDown --output plot_HEK/histogram/WT_sgB_R2_branch_30bpDown_insertion.png  --label_type absolute --variation_type insertion
python histogram.py --input data_HEK/output/WT_sgB_R2_branch_30bpDown --output plot_HEK/histogram/WT_sgB_R2_branch_30bpDown_substitution.png  --label_type absolute --variation_type substitution
python histogram.py --input data_HEK/output/WT_sgB_R2_branch --output plot_HEK/histogram/WT_sgB_R2_branch_deletion.png  --label_type relative --variation_type deletion
python histogram.py --input data_HEK/output/WT_sgB_R2_branch --output plot_HEK/histogram/WT_sgB_R2_branch_insertion.png  --label_type relative --variation_type insertion
python histogram.py --input data_HEK/output/WT_sgB_R2_branch_noDSB --output plot_HEK/histogram/WT_sgB_R2_branch_noDSB_deletion.png  --label_type relative --variation_type deletion
python histogram.py --input data_HEK/output/WT_sgB_R2_branch_noDSB --output plot_HEK/histogram/WT_sgB_R2_branch_noDSB_insertion.png  --label_type relative --variation_type insertion
python histogram.py --input data_HEK/output/WT_sgB_R2_branch_noDSB --output plot_HEK/histogram/WT_sgB_R2_branch_noDSB_substitution.png  --label_type relative --variation_type substitution
python histogram.py --input data_HEK/output/WT_sgB_R2_branch --output plot_HEK/histogram/WT_sgB_R2_branch_substitution.png  --label_type relative --variation_type substitution
python histogram.py --input data_HEK/output/WT_sgB_R2_cmv_30bpDown --output plot_HEK/histogram/WT_sgB_R2_cmv_30bpDown_deletion.png  --label_type absolute --variation_type deletion
python histogram.py --input data_HEK/output/WT_sgB_R2_cmv_30bpDown --output plot_HEK/histogram/WT_sgB_R2_cmv_30bpDown_insertion.png  --label_type absolute --variation_type insertion
python histogram.py --input data_HEK/output/WT_sgB_R2_cmv_30bpDown --output plot_HEK/histogram/WT_sgB_R2_cmv_30bpDown_substitution.png  --label_type absolute --variation_type substitution
python histogram.py --input data_HEK/output/WT_sgB_R2_cmv --output plot_HEK/histogram/WT_sgB_R2_cmv_deletion.png  --label_type relative --variation_type deletion
python histogram.py --input data_HEK/output/WT_sgB_R2_cmv --output plot_HEK/histogram/WT_sgB_R2_cmv_insertion.png  --label_type relative --variation_type insertion
python histogram.py --input data_HEK/output/WT_sgB_R2_cmv_noDSB --output plot_HEK/histogram/WT_sgB_R2_cmv_noDSB_deletion.png  --label_type relative --variation_type deletion
python histogram.py --input data_HEK/output/WT_sgB_R2_cmv_noDSB --output plot_HEK/histogram/WT_sgB_R2_cmv_noDSB_insertion.png  --label_type relative --variation_type insertion
python histogram.py --input data_HEK/output/WT_sgB_R2_cmv_noDSB --output plot_HEK/histogram/WT_sgB_R2_cmv_noDSB_substitution.png  --label_type relative --variation_type substitution
python histogram.py --input data_HEK/output/WT_sgB_R2_cmv --output plot_HEK/histogram/WT_sgB_R2_cmv_substitution.png  --label_type relative --variation_type substitution
python histogram.py --input data_HEK/output/WT_sgB_R2_sense_30bpDown --output plot_HEK/histogram/WT_sgB_R2_sense_30bpDown_deletion.png  --label_type absolute --variation_type deletion
python histogram.py --input data_HEK/output/WT_sgB_R2_sense_30bpDown --output plot_HEK/histogram/WT_sgB_R2_sense_30bpDown_insertion.png  --label_type absolute --variation_type insertion
python histogram.py --input data_HEK/output/WT_sgB_R2_sense_30bpDown --output plot_HEK/histogram/WT_sgB_R2_sense_30bpDown_substitution.png  --label_type absolute --variation_type substitution
python histogram.py --input data_HEK/output/WT_sgB_R2_sense --output plot_HEK/histogram/WT_sgB_R2_sense_deletion.png  --label_type relative --variation_type deletion
python histogram.py --input data_HEK/output/WT_sgB_R2_sense --output plot_HEK/histogram/WT_sgB_R2_sense_insertion.png  --label_type relative --variation_type insertion
python histogram.py --input data_HEK/output/WT_sgB_R2_sense_noDSB --output plot_HEK/histogram/WT_sgB_R2_sense_noDSB_deletion.png  --label_type relative --variation_type deletion
python histogram.py --input data_HEK/output/WT_sgB_R2_sense_noDSB --output plot_HEK/histogram/WT_sgB_R2_sense_noDSB_insertion.png  --label_type relative --variation_type insertion
python histogram.py --input data_HEK/output/WT_sgB_R2_sense_noDSB --output plot_HEK/histogram/WT_sgB_R2_sense_noDSB_substitution.png  --label_type relative --variation_type substitution
python histogram.py --input data_HEK/output/WT_sgB_R2_sense --output plot_HEK/histogram/WT_sgB_R2_sense_substitution.png  --label_type relative --variation_type substitution
python histogram.py --input data_HEK/output/WT_sgCD_R1_antisense_merged --output plot_HEK/histogram/WT_sgCD_R1_antisense_merged_deletion.png --reverse_pos --label_type relative --variation_type deletion
python histogram.py --input data_HEK/output/WT_sgCD_R1_antisense_merged --output plot_HEK/histogram/WT_sgCD_R1_antisense_merged_insertion.png --reverse_pos --label_type relative --variation_type insertion
python histogram.py --input data_HEK/output/WT_sgCD_R1_antisense_merged --output plot_HEK/histogram/WT_sgCD_R1_antisense_merged_substitution.png --reverse_pos --label_type relative --variation_type substitution
python histogram.py --input data_HEK/output/WT_sgCD_R1_antisense_new --output plot_HEK/histogram/WT_sgCD_R1_antisense_new_deletion.png --reverse_pos --label_type relative --variation_type deletion
python histogram.py --input data_HEK/output/WT_sgCD_R1_antisense_new --output plot_HEK/histogram/WT_sgCD_R1_antisense_new_insertion.png --reverse_pos --label_type relative --variation_type insertion
python histogram.py --input data_HEK/output/WT_sgCD_R1_antisense_new --output plot_HEK/histogram/WT_sgCD_R1_antisense_new_substitution.png --reverse_pos --label_type relative --variation_type substitution
python histogram.py --input data_HEK/output/WT_sgCD_R1_antisense_old --output plot_HEK/histogram/WT_sgCD_R1_antisense_old_deletion.png --reverse_pos --label_type relative --variation_type deletion
python histogram.py --input data_HEK/output/WT_sgCD_R1_antisense_old --output plot_HEK/histogram/WT_sgCD_R1_antisense_old_insertion.png --reverse_pos --label_type relative --variation_type insertion
python histogram.py --input data_HEK/output/WT_sgCD_R1_antisense_old --output plot_HEK/histogram/WT_sgCD_R1_antisense_old_substitution.png --reverse_pos --label_type relative --variation_type substitution
python histogram.py --input data_HEK/output/WT_sgCD_R1_splicing_merged --output plot_HEK/histogram/WT_sgCD_R1_splicing_merged_deletion.png --reverse_pos --label_type relative --variation_type deletion
python histogram.py --input data_HEK/output/WT_sgCD_R1_splicing_merged --output plot_HEK/histogram/WT_sgCD_R1_splicing_merged_insertion.png --reverse_pos --label_type relative --variation_type insertion
python histogram.py --input data_HEK/output/WT_sgCD_R1_splicing_merged --output plot_HEK/histogram/WT_sgCD_R1_splicing_merged_substitution.png --reverse_pos --label_type relative --variation_type substitution
python histogram.py --input data_HEK/output/WT_sgCD_R1_splicing_new --output plot_HEK/histogram/WT_sgCD_R1_splicing_new_deletion.png --reverse_pos --label_type relative --variation_type deletion
python histogram.py --input data_HEK/output/WT_sgCD_R1_splicing_new --output plot_HEK/histogram/WT_sgCD_R1_splicing_new_insertion.png --reverse_pos --label_type relative --variation_type insertion
python histogram.py --input data_HEK/output/WT_sgCD_R1_splicing_new --output plot_HEK/histogram/WT_sgCD_R1_splicing_new_substitution.png --reverse_pos --label_type relative --variation_type substitution
python histogram.py --input data_HEK/output/WT_sgCD_R1_splicing_old --output plot_HEK/histogram/WT_sgCD_R1_splicing_old_deletion.png --reverse_pos --label_type relative --variation_type deletion
python histogram.py --input data_HEK/output/WT_sgCD_R1_splicing_old --output plot_HEK/histogram/WT_sgCD_R1_splicing_old_insertion.png --reverse_pos --label_type relative --variation_type insertion
python histogram.py --input data_HEK/output/WT_sgCD_R1_splicing_old --output plot_HEK/histogram/WT_sgCD_R1_splicing_old_substitution.png --reverse_pos --label_type relative --variation_type substitution
python histogram.py --input data_HEK/output/WT_sgCD_R2_antisense_merged --output plot_HEK/histogram/WT_sgCD_R2_antisense_merged_deletion.png  --label_type relative --variation_type deletion
python histogram.py --input data_HEK/output/WT_sgCD_R2_antisense_merged --output plot_HEK/histogram/WT_sgCD_R2_antisense_merged_insertion.png  --label_type relative --variation_type insertion
python histogram.py --input data_HEK/output/WT_sgCD_R2_antisense_merged --output plot_HEK/histogram/WT_sgCD_R2_antisense_merged_substitution.png  --label_type relative --variation_type substitution
python histogram.py --input data_HEK/output/WT_sgCD_R2_antisense_new --output plot_HEK/histogram/WT_sgCD_R2_antisense_new_deletion.png  --label_type relative --variation_type deletion
python histogram.py --input data_HEK/output/WT_sgCD_R2_antisense_new --output plot_HEK/histogram/WT_sgCD_R2_antisense_new_insertion.png  --label_type relative --variation_type insertion
python histogram.py --input data_HEK/output/WT_sgCD_R2_antisense_new --output plot_HEK/histogram/WT_sgCD_R2_antisense_new_substitution.png  --label_type relative --variation_type substitution
python histogram.py --input data_HEK/output/WT_sgCD_R2_antisense_old --output plot_HEK/histogram/WT_sgCD_R2_antisense_old_deletion.png  --label_type relative --variation_type deletion
python histogram.py --input data_HEK/output/WT_sgCD_R2_antisense_old --output plot_HEK/histogram/WT_sgCD_R2_antisense_old_insertion.png  --label_type relative --variation_type insertion
python histogram.py --input data_HEK/output/WT_sgCD_R2_antisense_old --output plot_HEK/histogram/WT_sgCD_R2_antisense_old_substitution.png  --label_type relative --variation_type substitution
python histogram.py --input data_HEK/output/WT_sgCD_R2_splicing_merged --output plot_HEK/histogram/WT_sgCD_R2_splicing_merged_deletion.png  --label_type relative --variation_type deletion
python histogram.py --input data_HEK/output/WT_sgCD_R2_splicing_merged --output plot_HEK/histogram/WT_sgCD_R2_splicing_merged_insertion.png  --label_type relative --variation_type insertion
python histogram.py --input data_HEK/output/WT_sgCD_R2_splicing_merged --output plot_HEK/histogram/WT_sgCD_R2_splicing_merged_substitution.png  --label_type relative --variation_type substitution
python histogram.py --input data_HEK/output/WT_sgCD_R2_splicing_new --output plot_HEK/histogram/WT_sgCD_R2_splicing_new_deletion.png  --label_type relative --variation_type deletion
python histogram.py --input data_HEK/output/WT_sgCD_R2_splicing_new --output plot_HEK/histogram/WT_sgCD_R2_splicing_new_insertion.png  --label_type relative --variation_type insertion
python histogram.py --input data_HEK/output/WT_sgCD_R2_splicing_new --output plot_HEK/histogram/WT_sgCD_R2_splicing_new_substitution.png  --label_type relative --variation_type substitution
python histogram.py --input data_HEK/output/WT_sgCD_R2_splicing_old --output plot_HEK/histogram/WT_sgCD_R2_splicing_old_deletion.png  --label_type relative --variation_type deletion
python histogram.py --input data_HEK/output/WT_sgCD_R2_splicing_old --output plot_HEK/histogram/WT_sgCD_R2_splicing_old_insertion.png  --label_type relative --variation_type insertion
python histogram.py --input data_HEK/output/WT_sgCD_R2_splicing_old --output plot_HEK/histogram/WT_sgCD_R2_splicing_old_substitution.png  --label_type relative --variation_type substitution
