### Preprocessing ###
# The 0_align and 1_filter stages have been done on another machine,
# so we do only stages 2_combine, 3_window, 4_graph, and 5_histogram here.
python preprocess.py --ref_seq_file data_HEK/input/ref_seq/2DSB_R1_branch.fa --output data_HEK/output/KO_sgAB_R1_branch --dsb_pos 67 --label KO_sgAB_R1_branch --total_reads 13912975 15839537 13872702 13493608 --stages 2_combine 3_window 4_graph 5_histogram
python preprocess.py --ref_seq_file data_HEK/input/ref_seq/2DSB_R1_cmv.fa --output data_HEK/output/KO_sgAB_R1_cmv --dsb_pos 67 --label KO_sgAB_R1_cmv --total_reads 11307677 11757615 10272339 9412394 --stages 2_combine 3_window 4_graph 5_histogram
python preprocess.py --ref_seq_file data_HEK/input/ref_seq/2DSB_R1_sense.fa --output data_HEK/output/KO_sgAB_R1_sense --dsb_pos 67 --label KO_sgAB_R1_sense --total_reads 11320509 12480734 12500966 12479012 --stages 2_combine 3_window 4_graph 5_histogram
python preprocess.py --ref_seq_file data_HEK/input/ref_seq/2DSB_R2_branch.fa --output data_HEK/output/KO_sgAB_R2_branch --dsb_pos 46 --label KO_sgAB_R2_branch --total_reads 12987477 14745821 12946604 12582077 --stages 2_combine 3_window 4_graph 5_histogram
python preprocess.py --ref_seq_file data_HEK/input/ref_seq/2DSB_R2_cmv.fa --output data_HEK/output/KO_sgAB_R2_cmv --dsb_pos 46 --label KO_sgAB_R2_cmv --total_reads 10562895 10985096 9559721 8729797 --stages 2_combine 3_window 4_graph 5_histogram
python preprocess.py --ref_seq_file data_HEK/input/ref_seq/2DSB_R2_sense.fa --output data_HEK/output/KO_sgAB_R2_sense --dsb_pos 46 --label KO_sgAB_R2_sense --total_reads 10142826 11211467 11130391 11080481 --stages 2_combine 3_window 4_graph 5_histogram
python preprocess.py --ref_seq_file data_HEK/input/ref_seq/1DSB_R1_branch.fa --output data_HEK/output/KO_sgA_R1_branch --dsb_pos 67 --label KO_sgA_R1_branch --total_reads 11021111 11280773 12426852 11659042 --stages 2_combine 3_window 4_graph 5_histogram
python preprocess.py --ref_seq_file data_HEK/input/ref_seq/1DSB_R1_branch.fa --output data_HEK/output/KO_sgA_R1_branch_30bpDown --dsb_pos 97 --label KO_sgA_R1_branch_30bpDown --total_reads 11021111 11280773 12426852 11659042 --stages 2_combine 3_window 4_graph 5_histogram
python preprocess.py --ref_seq_file data_HEK/input/ref_seq/1DSB_R1_branch.fa --output data_HEK/output/KO_sgA_R1_branch_nodsb --dsb_pos 67 --label KO_sgA_R1_branch_nodsb --total_reads 10190833 --stages 2_combine 3_window 4_graph 5_histogram
python preprocess.py --ref_seq_file data_HEK/input/ref_seq/1DSB_R1_cmv.fa --output data_HEK/output/KO_sgA_R1_cmv --dsb_pos 67 --label KO_sgA_R1_cmv --total_reads 9933546 10351309 9388188 8668198 --stages 2_combine 3_window 4_graph 5_histogram
python preprocess.py --ref_seq_file data_HEK/input/ref_seq/1DSB_R1_cmv.fa --output data_HEK/output/KO_sgA_R1_cmv_30bpDown --dsb_pos 97 --label KO_sgA_R1_cmv_30bpDown --total_reads 9933546 10351309 9388188 8668198 --stages 2_combine 3_window 4_graph 5_histogram
python preprocess.py --ref_seq_file data_HEK/input/ref_seq/1DSB_R1_cmv.fa --output data_HEK/output/KO_sgA_R1_cmv_nodsb --dsb_pos 67 --label KO_sgA_R1_cmv_nodsb --total_reads 7763439 --stages 2_combine 3_window 4_graph 5_histogram
python preprocess.py --ref_seq_file data_HEK/input/ref_seq/1DSB_R1_sense.fa --output data_HEK/output/KO_sgA_R1_sense --dsb_pos 67 --label KO_sgA_R1_sense --total_reads 8597510 10116623 8703707 9021103 --stages 2_combine 3_window 4_graph 5_histogram
python preprocess.py --ref_seq_file data_HEK/input/ref_seq/1DSB_R1_sense.fa --output data_HEK/output/KO_sgA_R1_sense_30bpDown --dsb_pos 97 --label KO_sgA_R1_sense_30bpDown --total_reads 8597510 10116623 8703707 9021103 --stages 2_combine 3_window 4_graph 5_histogram
python preprocess.py --ref_seq_file data_HEK/input/ref_seq/1DSB_R1_sense.fa --output data_HEK/output/KO_sgA_R1_sense_nodsb --dsb_pos 67 --label KO_sgA_R1_sense_nodsb --total_reads 7424148 --stages 2_combine 3_window 4_graph 5_histogram
python preprocess.py --ref_seq_file data_HEK/input/ref_seq/1DSB_R2_branch.fa --output data_HEK/output/KO_sgB_R2_branch --dsb_pos 46 --label KO_sgB_R2_branch --total_reads 9730255 10430885 9770845 10249893 --stages 2_combine 3_window 4_graph 5_histogram
python preprocess.py --ref_seq_file data_HEK/input/ref_seq/1DSB_R2_branch.fa --output data_HEK/output/KO_sgB_R2_branch_30bpDown --dsb_pos 76 --label KO_sgB_R2_branch_30bpDown --total_reads 9730255 10430885 9770845 10249893 --stages 2_combine 3_window 4_graph 5_histogram
python preprocess.py --ref_seq_file data_HEK/input/ref_seq/1DSB_R2_branch.fa --output data_HEK/output/KO_sgB_R2_branch_nodsb --dsb_pos 46 --label KO_sgB_R2_branch_nodsb --total_reads 10027116 --stages 2_combine 3_window 4_graph 5_histogram
python preprocess.py --ref_seq_file data_HEK/input/ref_seq/1DSB_R2_cmv.fa --output data_HEK/output/KO_sgB_R2_cmv --dsb_pos 46 --label KO_sgB_R2_cmv --total_reads 6718301 6435913 7285831 6372479 --stages 2_combine 3_window 4_graph 5_histogram
python preprocess.py --ref_seq_file data_HEK/input/ref_seq/1DSB_R2_cmv.fa --output data_HEK/output/KO_sgB_R2_cmv_30bpDown --dsb_pos 76 --label KO_sgB_R2_cmv_30bpDown --total_reads 6718301 6435913 7285831 6372479 --stages 2_combine 3_window 4_graph 5_histogram
python preprocess.py --ref_seq_file data_HEK/input/ref_seq/1DSB_R2_cmv.fa --output data_HEK/output/KO_sgB_R2_cmv_nodsb --dsb_pos 46 --label KO_sgB_R2_cmv_nodsb --total_reads 7622513 --stages 2_combine 3_window 4_graph 5_histogram
python preprocess.py --ref_seq_file data_HEK/input/ref_seq/1DSB_R2_sense.fa --output data_HEK/output/KO_sgB_R2_sense --dsb_pos 46 --label KO_sgB_R2_sense --total_reads 6494964 7011524 7131423 6545416 --stages 2_combine 3_window 4_graph 5_histogram
python preprocess.py --ref_seq_file data_HEK/input/ref_seq/1DSB_R2_sense.fa --output data_HEK/output/KO_sgB_R2_sense_30bpDown --dsb_pos 76 --label KO_sgB_R2_sense_30bpDown --total_reads 6494964 7011524 7131423 6545416 --stages 2_combine 3_window 4_graph 5_histogram
python preprocess.py --ref_seq_file data_HEK/input/ref_seq/1DSB_R2_sense.fa --output data_HEK/output/KO_sgB_R2_sense_nodsb --dsb_pos 46 --label KO_sgB_R2_sense_nodsb --total_reads 7181166 --stages 2_combine 3_window 4_graph 5_histogram
python preprocess.py --ref_seq_file data_HEK/input/ref_seq/2DSB_R1_branch.fa --output data_HEK/output/WT_sgAB_R1_branch --dsb_pos 67 --label WT_sgAB_R1_branch --total_reads 9021462 9430938 9051278 9192054 --stages 2_combine 3_window 4_graph 5_histogram
python preprocess.py --ref_seq_file data_HEK/input/ref_seq/2DSB_R1_cmv.fa --output data_HEK/output/WT_sgAB_R1_cmv --dsb_pos 67 --label WT_sgAB_R1_cmv --total_reads 7604379 8885716 8150455 7694818 --stages 2_combine 3_window 4_graph 5_histogram
python preprocess.py --ref_seq_file data_HEK/input/ref_seq/2DSB_R1_sense.fa --output data_HEK/output/WT_sgAB_R1_sense --dsb_pos 67 --label WT_sgAB_R1_sense --total_reads 6630053 7246619 8069391 7513691 --stages 2_combine 3_window 4_graph 5_histogram
python preprocess.py --ref_seq_file data_HEK/input/ref_seq/2DSB_R2_branch.fa --output data_HEK/output/WT_sgAB_R2_branch --dsb_pos 46 --label WT_sgAB_R2_branch --total_reads 8525251 8875435 8522228 8656502 --stages 2_combine 3_window 4_graph 5_histogram
python preprocess.py --ref_seq_file data_HEK/input/ref_seq/2DSB_R2_cmv.fa --output data_HEK/output/WT_sgAB_R2_cmv --dsb_pos 46 --label WT_sgAB_R2_cmv --total_reads 6898791 7986453 7354088 6940576 --stages 2_combine 3_window 4_graph 5_histogram
python preprocess.py --ref_seq_file data_HEK/input/ref_seq/2DSB_R2_sense.fa --output data_HEK/output/WT_sgAB_R2_sense --dsb_pos 46 --label WT_sgAB_R2_sense --total_reads 6177083 6744517 7507107 7001340 --stages 2_combine 3_window 4_graph 5_histogram
python preprocess.py --ref_seq_file data_HEK/input/ref_seq/1DSB_R1_branch.fa --output data_HEK/output/WT_sgA_R1_branch --dsb_pos 67 --label WT_sgA_R1_branch --total_reads 8808358 9297647 9399483 8799841 --stages 2_combine 3_window 4_graph 5_histogram
python preprocess.py --ref_seq_file data_HEK/input/ref_seq/1DSB_R1_branch.fa --output data_HEK/output/WT_sgA_R1_branch_30bpDown --dsb_pos 97 --label WT_sgA_R1_branch_30bpDown --total_reads 8808358 9297647 9399483 8799841 --stages 2_combine 3_window 4_graph 5_histogram
python preprocess.py --ref_seq_file data_HEK/input/ref_seq/1DSB_R1_branch.fa --output data_HEK/output/WT_sgA_R1_branch_nodsb --dsb_pos 67 --label WT_sgA_R1_branch_nodsb --total_reads 12898941 --stages 2_combine 3_window 4_graph 5_histogram
python preprocess.py --ref_seq_file data_HEK/input/ref_seq/1DSB_R1_cmv.fa --output data_HEK/output/WT_sgA_R1_cmv --dsb_pos 67 --label WT_sgA_R1_cmv --total_reads 8171224 8180897 8314116 8096639 --stages 2_combine 3_window 4_graph 5_histogram
python preprocess.py --ref_seq_file data_HEK/input/ref_seq/1DSB_R1_cmv.fa --output data_HEK/output/WT_sgA_R1_cmv_30bpDown --dsb_pos 97 --label WT_sgA_R1_cmv_30bpDown --total_reads 8171224 8180897 8314116 8096639 --stages 2_combine 3_window 4_graph 5_histogram
python preprocess.py --ref_seq_file data_HEK/input/ref_seq/1DSB_R1_cmv.fa --output data_HEK/output/WT_sgA_R1_cmv_nodsb --dsb_pos 67 --label WT_sgA_R1_cmv_nodsb --total_reads 10217401 --stages 2_combine 3_window 4_graph 5_histogram
python preprocess.py --ref_seq_file data_HEK/input/ref_seq/1DSB_R1_sense.fa --output data_HEK/output/WT_sgA_R1_sense --dsb_pos 67 --label WT_sgA_R1_sense --total_reads 7579965 7982725 7854740 7534924 --stages 2_combine 3_window 4_graph 5_histogram
python preprocess.py --ref_seq_file data_HEK/input/ref_seq/1DSB_R1_sense.fa --output data_HEK/output/WT_sgA_R1_sense_30bpDown --dsb_pos 97 --label WT_sgA_R1_sense_30bpDown --total_reads 7579965 7982725 7854740 7534924 --stages 2_combine 3_window 4_graph 5_histogram
python preprocess.py --ref_seq_file data_HEK/input/ref_seq/1DSB_R1_sense.fa --output data_HEK/output/WT_sgA_R1_sense_nodsb --dsb_pos 67 --label WT_sgA_R1_sense_nodsb --total_reads 10005232 --stages 2_combine 3_window 4_graph 5_histogram
python preprocess.py --ref_seq_file data_HEK/input/ref_seq/1DSB_R2_branch.fa --output data_HEK/output/WT_sgB_R2_branch --dsb_pos 46 --label WT_sgB_R2_branch --total_reads 9524548 10125834 10173904 9525100 --stages 2_combine 3_window 4_graph 5_histogram
python preprocess.py --ref_seq_file data_HEK/input/ref_seq/1DSB_R2_branch.fa --output data_HEK/output/WT_sgB_R2_branch_30bpDown --dsb_pos 76 --label WT_sgB_R2_branch_30bpDown --total_reads 9524548 10125834 10173904 9525100 --stages 2_combine 3_window 4_graph 5_histogram
python preprocess.py --ref_seq_file data_HEK/input/ref_seq/1DSB_R2_branch.fa --output data_HEK/output/WT_sgB_R2_branch_nodsb --dsb_pos 46 --label WT_sgB_R2_branch_nodsb --total_reads 12461219 --stages 2_combine 3_window 4_graph 5_histogram
python preprocess.py --ref_seq_file data_HEK/input/ref_seq/1DSB_R2_cmv.fa --output data_HEK/output/WT_sgB_R2_cmv --dsb_pos 46 --label WT_sgB_R2_cmv --total_reads 7280860 6872217 6847531 7081713 --stages 2_combine 3_window 4_graph 5_histogram
python preprocess.py --ref_seq_file data_HEK/input/ref_seq/1DSB_R2_cmv.fa --output data_HEK/output/WT_sgB_R2_cmv_30bpDown --dsb_pos 76 --label WT_sgB_R2_cmv_30bpDown --total_reads 7280860 6872217 6847531 7081713 --stages 2_combine 3_window 4_graph 5_histogram
python preprocess.py --ref_seq_file data_HEK/input/ref_seq/1DSB_R2_cmv.fa --output data_HEK/output/WT_sgB_R2_cmv_nodsb --dsb_pos 46 --label WT_sgB_R2_cmv_nodsb --total_reads 9853052 --stages 2_combine 3_window 4_graph 5_histogram
python preprocess.py --ref_seq_file data_HEK/input/ref_seq/1DSB_R2_sense.fa --output data_HEK/output/WT_sgB_R2_sense --dsb_pos 46 --label WT_sgB_R2_sense --total_reads 7137355 6618133 8227882 7238408 --stages 2_combine 3_window 4_graph 5_histogram
python preprocess.py --ref_seq_file data_HEK/input/ref_seq/1DSB_R2_sense.fa --output data_HEK/output/WT_sgB_R2_sense_30bpDown --dsb_pos 76 --label WT_sgB_R2_sense_30bpDown --total_reads 7137355 6618133 8227882 7238408 --stages 2_combine 3_window 4_graph 5_histogram
python preprocess.py --ref_seq_file data_HEK/input/ref_seq/1DSB_R2_sense.fa --output data_HEK/output/WT_sgB_R2_sense_nodsb --dsb_pos 46 --label WT_sgB_R2_sense_nodsb --total_reads 9354510 --stages 2_combine 3_window 4_graph 5_histogram
python preprocess.py --ref_seq_file data_HEK/input/ref_seq/2DSB_R1_antisense_new.fa --output data_HEK/output/WT_sgCD_R1_antisense_new --dsb_pos 66 --label WT_sgCD_R1_antisense_new --total_reads 6302370 5988345 5741048 5405939 --stages 2_combine 3_window 4_graph 5_histogram
python preprocess.py --ref_seq_file data_HEK/input/ref_seq/2DSB_R1_antisense_old.fa --output data_HEK/output/WT_sgCD_R1_antisense_old --dsb_pos 50 --label WT_sgCD_R1_antisense_old --total_reads 7813781 7486736 8114856 6586577 --stages 2_combine 3_window 4_graph 5_histogram
python preprocess.py --ref_seq_file data_HEK/input/ref_seq/2DSB_R1_splicing_new.fa --output data_HEK/output/WT_sgCD_R1_splicing_new --dsb_pos 66 --label WT_sgCD_R1_splicing_new --total_reads 4177291 4647120 4405688 5054324 --stages 2_combine 3_window 4_graph 5_histogram
python preprocess.py --ref_seq_file data_HEK/input/ref_seq/2DSB_R1_splicing_old.fa --output data_HEK/output/WT_sgCD_R1_splicing_old --dsb_pos 50 --label WT_sgCD_R1_splicing_old --total_reads 9334492 9142001 8497185 8346242 --stages 2_combine 3_window 4_graph 5_histogram
python preprocess.py --ref_seq_file data_HEK/input/ref_seq/2DSB_R2_antisense_new.fa --output data_HEK/output/WT_sgCD_R2_antisense_new --dsb_pos 47 --label WT_sgCD_R2_antisense_new --total_reads 6161112 5856132 5613583 5281487 --stages 2_combine 3_window 4_graph 5_histogram
python preprocess.py --ref_seq_file data_HEK/input/ref_seq/2DSB_R2_antisense_old.fa --output data_HEK/output/WT_sgCD_R2_antisense_old --dsb_pos 47 --label WT_sgCD_R2_antisense_old --total_reads 7813781 7486736 8114856 6586577 --stages 2_combine 3_window 4_graph 5_histogram
python preprocess.py --ref_seq_file data_HEK/input/ref_seq/2DSB_R2_splicing_new.fa --output data_HEK/output/WT_sgCD_R2_splicing_new --dsb_pos 47 --label WT_sgCD_R2_splicing_new --total_reads 4062558 4535123 4280724 4926338 --stages 2_combine 3_window 4_graph 5_histogram
python preprocess.py --ref_seq_file data_HEK/input/ref_seq/2DSB_R2_splicing_old.fa --output data_HEK/output/WT_sgCD_R2_splicing_old --dsb_pos 47 --label WT_sgCD_R2_splicing_old --total_reads 9334492 9142001 8497185 8346242 --stages 2_combine 3_window 4_graph 5_histogram

### Get comparison data ###
python comparison.py --input data_HEK/output/KO_sgAB_R1_sense data_HEK/output/KO_sgAB_R1_branch --output data_HEK/output/KO_sgAB_R1_sense_branch
python comparison.py --input data_HEK/output/KO_sgAB_R1_sense data_HEK/output/KO_sgAB_R1_cmv --output data_HEK/output/KO_sgAB_R1_sense_cmv
python comparison.py --input data_HEK/output/KO_sgAB_R2_sense data_HEK/output/KO_sgAB_R2_branch --output data_HEK/output/KO_sgAB_R2_sense_branch
python comparison.py --input data_HEK/output/KO_sgAB_R2_sense data_HEK/output/KO_sgAB_R2_cmv --output data_HEK/output/KO_sgAB_R2_sense_cmv
python comparison.py --input data_HEK/output/KO_sgA_R1_sense data_HEK/output/KO_sgA_R1_branch --output data_HEK/output/KO_sgA_R1_sense_branch
python comparison.py --input data_HEK/output/KO_sgA_R1_sense data_HEK/output/KO_sgA_R1_cmv --output data_HEK/output/KO_sgA_R1_sense_cmv
python comparison.py --input data_HEK/output/KO_sgB_R2_sense data_HEK/output/KO_sgB_R2_branch --output data_HEK/output/KO_sgB_R2_sense_branch
python comparison.py --input data_HEK/output/KO_sgB_R2_sense data_HEK/output/KO_sgB_R2_cmv --output data_HEK/output/KO_sgB_R2_sense_cmv
python comparison.py --input data_HEK/output/WT_sgAB_R1_sense data_HEK/output/WT_sgAB_R1_branch --output data_HEK/output/WT_sgAB_R1_sense_branch
python comparison.py --input data_HEK/output/WT_sgAB_R1_sense data_HEK/output/WT_sgAB_R1_cmv --output data_HEK/output/WT_sgAB_R1_sense_cmv
python comparison.py --input data_HEK/output/WT_sgAB_R2_sense data_HEK/output/WT_sgAB_R2_branch --output data_HEK/output/WT_sgAB_R2_sense_branch
python comparison.py --input data_HEK/output/WT_sgAB_R2_sense data_HEK/output/WT_sgAB_R2_cmv --output data_HEK/output/WT_sgAB_R2_sense_cmv
python comparison.py --input data_HEK/output/WT_sgA_R1_sense data_HEK/output/WT_sgA_R1_branch --output data_HEK/output/WT_sgA_R1_sense_branch
python comparison.py --input data_HEK/output/WT_sgA_R1_sense data_HEK/output/WT_sgA_R1_cmv --output data_HEK/output/WT_sgA_R1_sense_cmv
python comparison.py --input data_HEK/output/WT_sgB_R2_sense data_HEK/output/WT_sgB_R2_branch --output data_HEK/output/WT_sgB_R2_sense_branch
python comparison.py --input data_HEK/output/WT_sgB_R2_sense data_HEK/output/WT_sgB_R2_cmv --output data_HEK/output/WT_sgB_R2_sense_cmv
python comparison.py --input data_HEK/output/WT_sgCD_R1_antisense_new data_HEK/output/WT_sgCD_R1_splicing_new --output data_HEK/output/WT_sgCD_R1_antisense_splicing_new
python comparison.py --input data_HEK/output/WT_sgCD_R1_antisense_old data_HEK/output/WT_sgCD_R1_splicing_old --output data_HEK/output/WT_sgCD_R1_antisense_splicing_old
python comparison.py --input data_HEK/output/WT_sgCD_R2_antisense_new data_HEK/output/WT_sgCD_R2_splicing_new --output data_HEK/output/WT_sgCD_R2_antisense_splicing_new
python comparison.py --input data_HEK/output/WT_sgCD_R2_antisense_old data_HEK/output/WT_sgCD_R2_splicing_old --output data_HEK/output/WT_sgCD_R2_antisense_splicing_old

### Plot individual graphs ###
python graph.py --input data_HEK/output/KO_sgAB_R1_branch --output plot_HEK/graph/individual/KO_sgAB_R1_branch.png --layout universal_layout --width 2400 --height 1800 --range_x -12 13 --range_y -22 22 --universal_layout_y_axis_x_pos 12 --universal_layout_y_axis_y_range -19.5 20.5 --universal_layout_y_axis_insertion_max_tick 7 --universal_layout_y_axis_deletion_max_tick 17
python graph.py --input data_HEK/output/KO_sgAB_R1_cmv --output plot_HEK/graph/individual/KO_sgAB_R1_cmv.png --layout universal_layout --width 2400 --height 1800 --range_x -12 13 --range_y -22 22 --universal_layout_y_axis_x_pos 12 --universal_layout_y_axis_y_range -19.5 20.5 --universal_layout_y_axis_insertion_max_tick 7 --universal_layout_y_axis_deletion_max_tick 17
python graph.py --input data_HEK/output/KO_sgAB_R1_sense --output plot_HEK/graph/individual/KO_sgAB_R1_sense.png --layout universal_layout --width 2400 --height 1800 --range_x -12 13 --range_y -22 22 --universal_layout_y_axis_x_pos 12 --universal_layout_y_axis_y_range -19.5 20.5 --universal_layout_x_axis_deletion_y_pos -20.5 --universal_layout_x_axis_insertion_y_pos 21.5 --universal_layout_x_axis_x_range -11.5 11.5 --universal_layout_y_axis_insertion_max_tick 7 --universal_layout_y_axis_deletion_max_tick 17
python graph.py --input data_HEK/output/KO_sgAB_R2_branch --output plot_HEK/graph/individual/KO_sgAB_R2_branch.png --layout universal_layout --reverse_complement 1 --width 2400 --height 1800 --range_x -12 13 --range_y -22 22 --universal_layout_y_axis_x_pos 12 --universal_layout_y_axis_y_range -19.5 20.5 --universal_layout_y_axis_insertion_max_tick 7 --universal_layout_y_axis_deletion_max_tick 17
python graph.py --input data_HEK/output/KO_sgAB_R2_cmv --output plot_HEK/graph/individual/KO_sgAB_R2_cmv.png --layout universal_layout --reverse_complement 1 --width 2400 --height 1800 --range_x -12 13 --range_y -22 22 --universal_layout_y_axis_x_pos 12 --universal_layout_y_axis_y_range -19.5 20.5 --universal_layout_y_axis_insertion_max_tick 7 --universal_layout_y_axis_deletion_max_tick 17
python graph.py --input data_HEK/output/KO_sgAB_R2_sense --output plot_HEK/graph/individual/KO_sgAB_R2_sense.png --layout universal_layout --reverse_complement 1 --width 2400 --height 1800 --range_x -12 13 --range_y -22 22 --universal_layout_y_axis_x_pos 12 --universal_layout_y_axis_y_range -19.5 20.5 --universal_layout_y_axis_insertion_max_tick 7 --universal_layout_y_axis_deletion_max_tick 17
python graph.py --input data_HEK/output/KO_sgA_R1_branch --output plot_HEK/graph/individual/KO_sgA_R1_branch.png --layout universal_layout --width 2400 --height 1800 --range_x -12 13 --range_y -23 20 --universal_layout_y_axis_x_pos 12 --universal_layout_y_axis_y_range -20.5 18.5 --universal_layout_y_axis_insertion_max_tick 6 --universal_layout_y_axis_deletion_max_tick 19
python graph.py --input data_HEK/output/KO_sgA_R1_cmv --output plot_HEK/graph/individual/KO_sgA_R1_cmv.png --layout universal_layout --width 2400 --height 1800 --range_x -12 13 --range_y -23 20 --universal_layout_y_axis_x_pos 12 --universal_layout_y_axis_y_range -20.5 18.5 --universal_layout_y_axis_insertion_max_tick 6 --universal_layout_y_axis_deletion_max_tick 19
python graph.py --input data_HEK/output/KO_sgA_R1_sense --output plot_HEK/graph/individual/KO_sgA_R1_sense.png --layout universal_layout --width 2400 --height 1800 --range_x -12 13 --range_y -23 20 --universal_layout_y_axis_x_pos 12 --universal_layout_y_axis_y_range -20.5 18.5 --universal_layout_x_axis_deletion_y_pos -21.5 --universal_layout_x_axis_insertion_y_pos 19.5 --universal_layout_x_axis_x_range -11.5 11.5 --universal_layout_y_axis_insertion_max_tick 6 --universal_layout_y_axis_deletion_max_tick 19
python graph.py --input data_HEK/output/KO_sgB_R2_branch --output plot_HEK/graph/individual/KO_sgB_R2_branch.png --layout universal_layout --reverse_complement 1 --width 2400 --height 1800 --range_x -12 13 --range_y -22 16 --universal_layout_y_axis_x_pos 12 --universal_layout_y_axis_y_range -19.5 14.5 --universal_layout_y_axis_insertion_max_tick 5 --universal_layout_y_axis_deletion_max_tick 18
python graph.py --input data_HEK/output/KO_sgB_R2_cmv --output plot_HEK/graph/individual/KO_sgB_R2_cmv.png --layout universal_layout --reverse_complement 1 --width 2400 --height 1800 --range_x -12 13 --range_y -22 16 --universal_layout_y_axis_x_pos 12 --universal_layout_y_axis_y_range -19.5 14.5 --universal_layout_y_axis_insertion_max_tick 5 --universal_layout_y_axis_deletion_max_tick 18
python graph.py --input data_HEK/output/KO_sgB_R2_sense --output plot_HEK/graph/individual/KO_sgB_R2_sense.png --layout universal_layout --reverse_complement 1 --width 2400 --height 1800 --range_x -12 13 --range_y -22 16 --universal_layout_y_axis_x_pos 12 --universal_layout_y_axis_y_range -19.5 14.5 --universal_layout_y_axis_insertion_max_tick 5 --universal_layout_y_axis_deletion_max_tick 18
python graph.py --input data_HEK/output/WT_sgAB_R1_branch --output plot_HEK/graph/individual/WT_sgAB_R1_branch.png --layout universal_layout --width 2400 --height 1800 --range_x -12 13 --range_y -22 22 --universal_layout_y_axis_x_pos 12 --universal_layout_y_axis_y_range -19.5 20.5 --universal_layout_y_axis_insertion_max_tick 7 --universal_layout_y_axis_deletion_max_tick 17
python graph.py --input data_HEK/output/WT_sgAB_R1_cmv --output plot_HEK/graph/individual/WT_sgAB_R1_cmv.png --layout universal_layout --width 2400 --height 1800 --range_x -12 13 --range_y -22 22 --universal_layout_y_axis_x_pos 12 --universal_layout_y_axis_y_range -19.5 20.5 --universal_layout_y_axis_insertion_max_tick 7 --universal_layout_y_axis_deletion_max_tick 17
python graph.py --input data_HEK/output/WT_sgAB_R1_sense --output plot_HEK/graph/individual/WT_sgAB_R1_sense.png --layout universal_layout --width 2400 --height 1800 --range_x -12 13 --range_y -22 22 --universal_layout_y_axis_x_pos 12 --universal_layout_y_axis_y_range -19.5 20.5 --universal_layout_x_axis_deletion_y_pos -20.5 --universal_layout_x_axis_insertion_y_pos 21.5 --universal_layout_x_axis_x_range -11.5 11.5 --universal_layout_y_axis_insertion_max_tick 7 --universal_layout_y_axis_deletion_max_tick 17
python graph.py --input data_HEK/output/WT_sgAB_R2_branch --output plot_HEK/graph/individual/WT_sgAB_R2_branch.png --layout universal_layout --reverse_complement 1 --width 2400 --height 1800 --range_x -12 13 --range_y -22 22 --universal_layout_y_axis_x_pos 12 --universal_layout_y_axis_y_range -19.5 20.5 --universal_layout_y_axis_insertion_max_tick 7 --universal_layout_y_axis_deletion_max_tick 17
python graph.py --input data_HEK/output/WT_sgAB_R2_cmv --output plot_HEK/graph/individual/WT_sgAB_R2_cmv.png --layout universal_layout --reverse_complement 1 --width 2400 --height 1800 --range_x -12 13 --range_y -22 22 --universal_layout_y_axis_x_pos 12 --universal_layout_y_axis_y_range -19.5 20.5 --universal_layout_y_axis_insertion_max_tick 7 --universal_layout_y_axis_deletion_max_tick 17
python graph.py --input data_HEK/output/WT_sgAB_R2_sense --output plot_HEK/graph/individual/WT_sgAB_R2_sense.png --layout universal_layout --reverse_complement 1 --width 2400 --height 1800 --range_x -12 13 --range_y -22 22 --universal_layout_y_axis_x_pos 12 --universal_layout_y_axis_y_range -19.5 20.5 --universal_layout_y_axis_insertion_max_tick 7 --universal_layout_y_axis_deletion_max_tick 17
python graph.py --input data_HEK/output/WT_sgA_R1_branch --output plot_HEK/graph/individual/WT_sgA_R1_branch.png --layout universal_layout --width 2400 --height 1800 --range_x -12 13 --range_y -23 20 --universal_layout_y_axis_x_pos 12 --universal_layout_y_axis_y_range -20.5 18.5 --universal_layout_y_axis_insertion_max_tick 6 --universal_layout_y_axis_deletion_max_tick 19
python graph.py --input data_HEK/output/WT_sgA_R1_cmv --output plot_HEK/graph/individual/WT_sgA_R1_cmv.png --layout universal_layout --width 2400 --height 1800 --range_x -12 13 --range_y -23 20 --universal_layout_y_axis_x_pos 12 --universal_layout_y_axis_y_range -20.5 18.5 --universal_layout_y_axis_insertion_max_tick 6 --universal_layout_y_axis_deletion_max_tick 19
python graph.py --input data_HEK/output/WT_sgA_R1_sense --output plot_HEK/graph/individual/WT_sgA_R1_sense.png --layout universal_layout --width 2400 --height 1800 --range_x -12 13 --range_y -23 20 --universal_layout_y_axis_x_pos 12 --universal_layout_y_axis_y_range -20.5 18.5 --universal_layout_x_axis_deletion_y_pos -21.5 --universal_layout_x_axis_insertion_y_pos 19.5 --universal_layout_x_axis_x_range -11.5 11.5 --universal_layout_y_axis_insertion_max_tick 6 --universal_layout_y_axis_deletion_max_tick 19
python graph.py --input data_HEK/output/WT_sgB_R2_branch --output plot_HEK/graph/individual/WT_sgB_R2_branch.png --layout universal_layout --reverse_complement 1 --width 2400 --height 1800 --range_x -12 13 --range_y -22 16 --universal_layout_y_axis_x_pos 12 --universal_layout_y_axis_y_range -19.5 14.5 --universal_layout_y_axis_insertion_max_tick 5 --universal_layout_y_axis_deletion_max_tick 18
python graph.py --input data_HEK/output/WT_sgB_R2_cmv --output plot_HEK/graph/individual/WT_sgB_R2_cmv.png --layout universal_layout --reverse_complement 1 --width 2400 --height 1800 --range_x -12 13 --range_y -22 16 --universal_layout_y_axis_x_pos 12 --universal_layout_y_axis_y_range -19.5 14.5 --universal_layout_y_axis_insertion_max_tick 5 --universal_layout_y_axis_deletion_max_tick 18
python graph.py --input data_HEK/output/WT_sgB_R2_sense --output plot_HEK/graph/individual/WT_sgB_R2_sense.png --layout universal_layout --reverse_complement 1 --width 2400 --height 1800 --range_x -12 13 --range_y -22 16 --universal_layout_y_axis_x_pos 12 --universal_layout_y_axis_y_range -19.5 14.5 --universal_layout_y_axis_insertion_max_tick 5 --universal_layout_y_axis_deletion_max_tick 18
python graph.py --input data_HEK/output/WT_sgCD_R1_antisense_new --output plot_HEK/graph/individual/WT_sgCD_R1_antisense_new.png --layout universal_layout --width 2400 --height 1800 --range_x -12 13 --range_y -22 27 --universal_layout_y_axis_x_pos 12 --universal_layout_y_axis_y_range -19.5 25.5 --universal_layout_x_axis_deletion_y_pos -20.5 --universal_layout_x_axis_insertion_y_pos 26.5 --universal_layout_x_axis_x_range -11.5 11.5 --universal_layout_y_axis_insertion_max_tick 8 --universal_layout_y_axis_deletion_max_tick 17
python graph.py --input data_HEK/output/WT_sgCD_R1_antisense_old --output plot_HEK/graph/individual/WT_sgCD_R1_antisense_old.png --layout universal_layout --width 2400 --height 1800 --range_x -12 13 --range_y -22 27 --universal_layout_y_axis_x_pos 12 --universal_layout_y_axis_y_range -19.5 25.5 --universal_layout_x_axis_deletion_y_pos -20.5 --universal_layout_x_axis_insertion_y_pos 26.5 --universal_layout_x_axis_x_range -11.5 11.5 --universal_layout_y_axis_insertion_max_tick 8 --universal_layout_y_axis_deletion_max_tick 17
python graph.py --input data_HEK/output/WT_sgCD_R1_splicing_new --output plot_HEK/graph/individual/WT_sgCD_R1_splicing_new.png --layout universal_layout --width 2400 --height 1800 --range_x -12 13 --range_y -22 27 --universal_layout_y_axis_x_pos 12 --universal_layout_y_axis_y_range -19.5 25.5 --universal_layout_y_axis_insertion_max_tick 8 --universal_layout_y_axis_deletion_max_tick 17
python graph.py --input data_HEK/output/WT_sgCD_R1_splicing_old --output plot_HEK/graph/individual/WT_sgCD_R1_splicing_old.png --layout universal_layout --width 2400 --height 1800 --range_x -12 13 --range_y -22 27 --universal_layout_y_axis_x_pos 12 --universal_layout_y_axis_y_range -19.5 25.5 --universal_layout_y_axis_insertion_max_tick 8 --universal_layout_y_axis_deletion_max_tick 17
python graph.py --input data_HEK/output/WT_sgCD_R2_antisense_new --output plot_HEK/graph/individual/WT_sgCD_R2_antisense_new.png --layout universal_layout --reverse_complement 1 --width 2400 --height 1800 --range_x -12 13 --range_y -22 27 --universal_layout_y_axis_x_pos 12 --universal_layout_y_axis_y_range -19.5 25.5 --universal_layout_y_axis_insertion_max_tick 8 --universal_layout_y_axis_deletion_max_tick 17
python graph.py --input data_HEK/output/WT_sgCD_R2_antisense_old --output plot_HEK/graph/individual/WT_sgCD_R2_antisense_old.png --layout universal_layout --reverse_complement 1 --width 2400 --height 1800 --range_x -12 13 --range_y -22 27 --universal_layout_y_axis_x_pos 12 --universal_layout_y_axis_y_range -19.5 25.5 --universal_layout_y_axis_insertion_max_tick 8 --universal_layout_y_axis_deletion_max_tick 17
python graph.py --input data_HEK/output/WT_sgCD_R2_splicing_new --output plot_HEK/graph/individual/WT_sgCD_R2_splicing_new.png --layout universal_layout --reverse_complement 1 --width 2400 --height 1800 --range_x -12 13 --range_y -22 27 --universal_layout_y_axis_x_pos 12 --universal_layout_y_axis_y_range -19.5 25.5 --universal_layout_y_axis_insertion_max_tick 8 --universal_layout_y_axis_deletion_max_tick 17
python graph.py --input data_HEK/output/WT_sgCD_R2_splicing_old --output plot_HEK/graph/individual/WT_sgCD_R2_splicing_old.png --layout universal_layout --reverse_complement 1 --width 2400 --height 1800 --range_x -12 13 --range_y -22 27 --universal_layout_y_axis_x_pos 12 --universal_layout_y_axis_y_range -19.5 25.5 --universal_layout_y_axis_insertion_max_tick 8 --universal_layout_y_axis_deletion_max_tick 17

### Plot comparison graphs ##
python graph.py --input data_HEK/output/KO_sgAB_R1_sense_branch --output plot_HEK/graph/comparison/KO_sgAB_R1_sense_branch.png --layout universal_layout --width 2400 --height 1800 --range_x -12 13 --range_y -22 22 --universal_layout_y_axis_x_pos 12 --universal_layout_y_axis_y_range -19.5 20.5 --universal_layout_y_axis_insertion_max_tick 7 --universal_layout_y_axis_deletion_max_tick 17
python graph.py --input data_HEK/output/KO_sgAB_R1_sense_cmv --output plot_HEK/graph/comparison/KO_sgAB_R1_sense_cmv.png --layout universal_layout --width 2400 --height 1800 --range_x -12 13 --range_y -22 22 --universal_layout_y_axis_x_pos 12 --universal_layout_y_axis_y_range -19.5 20.5 --universal_layout_y_axis_insertion_max_tick 7 --universal_layout_y_axis_deletion_max_tick 17
python graph.py --input data_HEK/output/KO_sgAB_R2_sense_branch --output plot_HEK/graph/comparison/KO_sgAB_R2_sense_branch.png --layout universal_layout --reverse_complement 1 --width 2400 --height 1800 --range_x -12 13 --range_y -22 22 --universal_layout_y_axis_x_pos 12 --universal_layout_y_axis_y_range -19.5 20.5 --universal_layout_y_axis_insertion_max_tick 7 --universal_layout_y_axis_deletion_max_tick 17
python graph.py --input data_HEK/output/KO_sgAB_R2_sense_cmv --output plot_HEK/graph/comparison/KO_sgAB_R2_sense_cmv.png --layout universal_layout --reverse_complement 1 --width 2400 --height 1800 --range_x -12 13 --range_y -22 22 --universal_layout_y_axis_x_pos 12 --universal_layout_y_axis_y_range -19.5 20.5 --universal_layout_y_axis_insertion_max_tick 7 --universal_layout_y_axis_deletion_max_tick 17
python graph.py --input data_HEK/output/KO_sgA_R1_sense_branch --output plot_HEK/graph/comparison/KO_sgA_R1_sense_branch.png --layout universal_layout --width 2400 --height 1800 --range_x -12 13 --range_y -23 20 --universal_layout_y_axis_x_pos 12 --universal_layout_y_axis_y_range -20.5 18.5 --universal_layout_y_axis_insertion_max_tick 6 --universal_layout_y_axis_deletion_max_tick 19
python graph.py --input data_HEK/output/KO_sgA_R1_sense_cmv --output plot_HEK/graph/comparison/KO_sgA_R1_sense_cmv.png --layout universal_layout --width 2400 --height 1800 --range_x -12 13 --range_y -23 20 --universal_layout_y_axis_x_pos 12 --universal_layout_y_axis_y_range -20.5 18.5 --universal_layout_y_axis_insertion_max_tick 6 --universal_layout_y_axis_deletion_max_tick 19
python graph.py --input data_HEK/output/KO_sgB_R2_sense_branch --output plot_HEK/graph/comparison/KO_sgB_R2_sense_branch.png --layout universal_layout --reverse_complement 1 --width 2400 --height 1800 --range_x -12 13 --range_y -22 16 --universal_layout_y_axis_x_pos 12 --universal_layout_y_axis_y_range -19.5 14.5 --universal_layout_y_axis_insertion_max_tick 5 --universal_layout_y_axis_deletion_max_tick 18
python graph.py --input data_HEK/output/KO_sgB_R2_sense_cmv --output plot_HEK/graph/comparison/KO_sgB_R2_sense_cmv.png --layout universal_layout --reverse_complement 1 --width 2400 --height 1800 --range_x -12 13 --range_y -22 16 --universal_layout_y_axis_x_pos 12 --universal_layout_y_axis_y_range -19.5 14.5 --universal_layout_y_axis_insertion_max_tick 5 --universal_layout_y_axis_deletion_max_tick 18
python graph.py --input data_HEK/output/WT_sgAB_R1_sense_branch --output plot_HEK/graph/comparison/WT_sgAB_R1_sense_branch.png --layout universal_layout --width 2400 --height 1800 --range_x -12 13 --range_y -22 22 --universal_layout_y_axis_x_pos 12 --universal_layout_y_axis_y_range -19.5 20.5 --universal_layout_y_axis_insertion_max_tick 7 --universal_layout_y_axis_deletion_max_tick 17
python graph.py --input data_HEK/output/WT_sgAB_R1_sense_cmv --output plot_HEK/graph/comparison/WT_sgAB_R1_sense_cmv.png --layout universal_layout --width 2400 --height 1800 --range_x -12 13 --range_y -22 22 --universal_layout_y_axis_x_pos 12 --universal_layout_y_axis_y_range -19.5 20.5 --universal_layout_y_axis_insertion_max_tick 7 --universal_layout_y_axis_deletion_max_tick 17
python graph.py --input data_HEK/output/WT_sgAB_R2_sense_branch --output plot_HEK/graph/comparison/WT_sgAB_R2_sense_branch.png --layout universal_layout --reverse_complement 1 --width 2400 --height 1800 --range_x -12 13 --range_y -22 22 --universal_layout_y_axis_x_pos 12 --universal_layout_y_axis_y_range -19.5 20.5 --universal_layout_y_axis_insertion_max_tick 7 --universal_layout_y_axis_deletion_max_tick 17
python graph.py --input data_HEK/output/WT_sgAB_R2_sense_cmv --output plot_HEK/graph/comparison/WT_sgAB_R2_sense_cmv.png --layout universal_layout --reverse_complement 1 --width 2400 --height 1800 --range_x -12 13 --range_y -22 22 --universal_layout_y_axis_x_pos 12 --universal_layout_y_axis_y_range -19.5 20.5 --universal_layout_y_axis_insertion_max_tick 7 --universal_layout_y_axis_deletion_max_tick 17
python graph.py --input data_HEK/output/WT_sgA_R1_sense_branch --output plot_HEK/graph/comparison/WT_sgA_R1_sense_branch.png --layout universal_layout --width 2400 --height 1800 --range_x -12 13 --range_y -23 20 --universal_layout_y_axis_x_pos 12 --universal_layout_y_axis_y_range -20.5 18.5 --universal_layout_y_axis_insertion_max_tick 6 --universal_layout_y_axis_deletion_max_tick 19
python graph.py --input data_HEK/output/WT_sgA_R1_sense_cmv --output plot_HEK/graph/comparison/WT_sgA_R1_sense_cmv.png --layout universal_layout --width 2400 --height 1800 --range_x -12 13 --range_y -23 20 --universal_layout_y_axis_x_pos 12 --universal_layout_y_axis_y_range -20.5 18.5 --universal_layout_y_axis_insertion_max_tick 6 --universal_layout_y_axis_deletion_max_tick 19
python graph.py --input data_HEK/output/WT_sgB_R2_sense_branch --output plot_HEK/graph/comparison/WT_sgB_R2_sense_branch.png --layout universal_layout --reverse_complement 1 --width 2400 --height 1800 --range_x -12 13 --range_y -22 16 --universal_layout_y_axis_x_pos 12 --universal_layout_y_axis_y_range -19.5 14.5 --universal_layout_y_axis_insertion_max_tick 5 --universal_layout_y_axis_deletion_max_tick 18
python graph.py --input data_HEK/output/WT_sgB_R2_sense_cmv --output plot_HEK/graph/comparison/WT_sgB_R2_sense_cmv.png --layout universal_layout --reverse_complement 1 --width 2400 --height 1800 --range_x -12 13 --range_y -22 16 --universal_layout_y_axis_x_pos 12 --universal_layout_y_axis_y_range -19.5 14.5 --universal_layout_y_axis_insertion_max_tick 5 --universal_layout_y_axis_deletion_max_tick 18
python graph.py --input data_HEK/output/WT_sgCD_R1_antisense_splicing_new --output plot_HEK/graph/comparison/WT_sgCD_R1_antisense_splicing_new.png --layout universal_layout --width 2400 --height 1800 --range_x -12 13 --range_y -22 27 --universal_layout_y_axis_x_pos 12 --universal_layout_y_axis_y_range -19.5 25.5 --universal_layout_y_axis_insertion_max_tick 8 --universal_layout_y_axis_deletion_max_tick 17
python graph.py --input data_HEK/output/WT_sgCD_R1_antisense_splicing_old --output plot_HEK/graph/comparison/WT_sgCD_R1_antisense_splicing_old.png --layout universal_layout --width 2400 --height 1800 --range_x -12 13 --range_y -22 27 --universal_layout_y_axis_x_pos 12 --universal_layout_y_axis_y_range -19.5 25.5 --universal_layout_y_axis_insertion_max_tick 8 --universal_layout_y_axis_deletion_max_tick 17
python graph.py --input data_HEK/output/WT_sgCD_R2_antisense_splicing_new --output plot_HEK/graph/comparison/WT_sgCD_R2_antisense_splicing_new.png --layout universal_layout --reverse_complement 1 --width 2400 --height 1800 --range_x -12 13 --range_y -22 27 --universal_layout_y_axis_x_pos 12 --universal_layout_y_axis_y_range -19.5 25.5 --universal_layout_y_axis_insertion_max_tick 8 --universal_layout_y_axis_deletion_max_tick 17
python graph.py --input data_HEK/output/WT_sgCD_R2_antisense_splicing_old --output plot_HEK/graph/comparison/WT_sgCD_R2_antisense_splicing_old.png --layout universal_layout --reverse_complement 1 --width 2400 --height 1800 --range_x -12 13 --range_y -22 27 --universal_layout_y_axis_x_pos 12 --universal_layout_y_axis_y_range -19.5 25.5 --universal_layout_y_axis_insertion_max_tick 8 --universal_layout_y_axis_deletion_max_tick 17

### Plot histograms ###
python histogram.py --input data_HEK/output/KO_sgAB_R1_branch --output plot_HEK/histogram/KO_sgAB_R1_branch_deletion.png --color "#8080ff" --label_type relative --variation_type deletion
python histogram.py --input data_HEK/output/KO_sgAB_R1_branch --output plot_HEK/histogram/KO_sgAB_R1_branch_insertion.png --color "#ffa500" --label_type relative --variation_type insertion
python histogram.py --input data_HEK/output/KO_sgAB_R1_branch --output plot_HEK/histogram/KO_sgAB_R1_branch_substitution.png --color "#bfbfbf" --label_type relative --variation_type substitution
python histogram.py --input data_HEK/output/KO_sgAB_R1_cmv --output plot_HEK/histogram/KO_sgAB_R1_cmv_deletion.png --color "#8080ff" --label_type relative --variation_type deletion
python histogram.py --input data_HEK/output/KO_sgAB_R1_cmv --output plot_HEK/histogram/KO_sgAB_R1_cmv_insertion.png --color "#ffa500" --label_type relative --variation_type insertion
python histogram.py --input data_HEK/output/KO_sgAB_R1_cmv --output plot_HEK/histogram/KO_sgAB_R1_cmv_substitution.png --color "#bfbfbf" --label_type relative --variation_type substitution
python histogram.py --input data_HEK/output/KO_sgAB_R1_sense --output plot_HEK/histogram/KO_sgAB_R1_sense_deletion.png --color "#8080ff" --label_type relative --variation_type deletion
python histogram.py --input data_HEK/output/KO_sgAB_R1_sense --output plot_HEK/histogram/KO_sgAB_R1_sense_insertion.png --color "#ffa500" --label_type relative --variation_type insertion
python histogram.py --input data_HEK/output/KO_sgAB_R1_sense --output plot_HEK/histogram/KO_sgAB_R1_sense_substitution.png --color "#bfbfbf" --label_type relative --variation_type substitution
python histogram.py --input data_HEK/output/KO_sgAB_R2_branch --output plot_HEK/histogram/KO_sgAB_R2_branch_deletion.png --color "#8080ff" --reverse_pos --label_type relative --variation_type deletion
python histogram.py --input data_HEK/output/KO_sgAB_R2_branch --output plot_HEK/histogram/KO_sgAB_R2_branch_insertion.png --color "#ffa500" --reverse_pos --label_type relative --variation_type insertion
python histogram.py --input data_HEK/output/KO_sgAB_R2_branch --output plot_HEK/histogram/KO_sgAB_R2_branch_substitution.png --color "#bfbfbf" --reverse_pos --label_type relative --variation_type substitution
python histogram.py --input data_HEK/output/KO_sgAB_R2_cmv --output plot_HEK/histogram/KO_sgAB_R2_cmv_deletion.png --color "#8080ff" --reverse_pos --label_type relative --variation_type deletion
python histogram.py --input data_HEK/output/KO_sgAB_R2_cmv --output plot_HEK/histogram/KO_sgAB_R2_cmv_insertion.png --color "#ffa500" --reverse_pos --label_type relative --variation_type insertion
python histogram.py --input data_HEK/output/KO_sgAB_R2_cmv --output plot_HEK/histogram/KO_sgAB_R2_cmv_substitution.png --color "#bfbfbf" --reverse_pos --label_type relative --variation_type substitution
python histogram.py --input data_HEK/output/KO_sgAB_R2_sense --output plot_HEK/histogram/KO_sgAB_R2_sense_deletion.png --color "#8080ff" --reverse_pos --label_type relative --variation_type deletion
python histogram.py --input data_HEK/output/KO_sgAB_R2_sense --output plot_HEK/histogram/KO_sgAB_R2_sense_insertion.png --color "#ffa500" --reverse_pos --label_type relative --variation_type insertion
python histogram.py --input data_HEK/output/KO_sgAB_R2_sense --output plot_HEK/histogram/KO_sgAB_R2_sense_substitution.png --color "#bfbfbf" --reverse_pos --label_type relative --variation_type substitution
python histogram.py --input data_HEK/output/KO_sgA_R1_branch_30bpDown --output plot_HEK/histogram/KO_sgA_R1_branch_30bpDown_deletion.png --color "#8080ff" --label_type absolute --variation_type deletion
python histogram.py --input data_HEK/output/KO_sgA_R1_branch_30bpDown --output plot_HEK/histogram/KO_sgA_R1_branch_30bpDown_insertion.png --color "#ffa500" --label_type absolute --variation_type insertion
python histogram.py --input data_HEK/output/KO_sgA_R1_branch_30bpDown --output plot_HEK/histogram/KO_sgA_R1_branch_30bpDown_substitution.png --color "#bfbfbf" --label_type absolute --variation_type substitution
python histogram.py --input data_HEK/output/KO_sgA_R1_branch --output plot_HEK/histogram/KO_sgA_R1_branch_deletion.png --color "#8080ff" --label_type relative --variation_type deletion
python histogram.py --input data_HEK/output/KO_sgA_R1_branch --output plot_HEK/histogram/KO_sgA_R1_branch_insertion.png --color "#ffa500" --label_type relative --variation_type insertion
python histogram.py --input data_HEK/output/KO_sgA_R1_branch_noDSB --output plot_HEK/histogram/KO_sgA_R1_branch_noDSB_deletion.png --color "#8080ff" --label_type relative --variation_type deletion
python histogram.py --input data_HEK/output/KO_sgA_R1_branch_noDSB --output plot_HEK/histogram/KO_sgA_R1_branch_noDSB_insertion.png --color "#ffa500" --label_type relative --variation_type insertion
python histogram.py --input data_HEK/output/KO_sgA_R1_branch_noDSB --output plot_HEK/histogram/KO_sgA_R1_branch_noDSB_substitution.png --color "#bfbfbf" --label_type relative --variation_type substitution
python histogram.py --input data_HEK/output/KO_sgA_R1_branch --output plot_HEK/histogram/KO_sgA_R1_branch_substitution.png --color "#bfbfbf" --label_type relative --variation_type substitution
python histogram.py --input data_HEK/output/KO_sgA_R1_cmv_30bpDown --output plot_HEK/histogram/KO_sgA_R1_cmv_30bpDown_deletion.png --color "#8080ff" --label_type absolute --variation_type deletion
python histogram.py --input data_HEK/output/KO_sgA_R1_cmv_30bpDown --output plot_HEK/histogram/KO_sgA_R1_cmv_30bpDown_insertion.png --color "#ffa500" --label_type absolute --variation_type insertion
python histogram.py --input data_HEK/output/KO_sgA_R1_cmv_30bpDown --output plot_HEK/histogram/KO_sgA_R1_cmv_30bpDown_substitution.png --color "#bfbfbf" --label_type absolute --variation_type substitution
python histogram.py --input data_HEK/output/KO_sgA_R1_cmv --output plot_HEK/histogram/KO_sgA_R1_cmv_deletion.png --color "#8080ff" --label_type relative --variation_type deletion
python histogram.py --input data_HEK/output/KO_sgA_R1_cmv --output plot_HEK/histogram/KO_sgA_R1_cmv_insertion.png --color "#ffa500" --label_type relative --variation_type insertion
python histogram.py --input data_HEK/output/KO_sgA_R1_cmv_noDSB --output plot_HEK/histogram/KO_sgA_R1_cmv_noDSB_deletion.png --color "#8080ff" --label_type relative --variation_type deletion
python histogram.py --input data_HEK/output/KO_sgA_R1_cmv_noDSB --output plot_HEK/histogram/KO_sgA_R1_cmv_noDSB_insertion.png --color "#ffa500" --label_type relative --variation_type insertion
python histogram.py --input data_HEK/output/KO_sgA_R1_cmv_noDSB --output plot_HEK/histogram/KO_sgA_R1_cmv_noDSB_substitution.png --color "#bfbfbf" --label_type relative --variation_type substitution
python histogram.py --input data_HEK/output/KO_sgA_R1_cmv --output plot_HEK/histogram/KO_sgA_R1_cmv_substitution.png --color "#bfbfbf" --label_type relative --variation_type substitution
python histogram.py --input data_HEK/output/KO_sgA_R1_sense_30bpDown --output plot_HEK/histogram/KO_sgA_R1_sense_30bpDown_deletion.png --color "#8080ff" --label_type absolute --variation_type deletion
python histogram.py --input data_HEK/output/KO_sgA_R1_sense_30bpDown --output plot_HEK/histogram/KO_sgA_R1_sense_30bpDown_insertion.png --color "#ffa500" --label_type absolute --variation_type insertion
python histogram.py --input data_HEK/output/KO_sgA_R1_sense_30bpDown --output plot_HEK/histogram/KO_sgA_R1_sense_30bpDown_substitution.png --color "#bfbfbf" --label_type absolute --variation_type substitution
python histogram.py --input data_HEK/output/KO_sgA_R1_sense --output plot_HEK/histogram/KO_sgA_R1_sense_deletion.png --color "#8080ff" --label_type relative --variation_type deletion
python histogram.py --input data_HEK/output/KO_sgA_R1_sense --output plot_HEK/histogram/KO_sgA_R1_sense_insertion.png --color "#ffa500" --label_type relative --variation_type insertion
python histogram.py --input data_HEK/output/KO_sgA_R1_sense_noDSB --output plot_HEK/histogram/KO_sgA_R1_sense_noDSB_deletion.png --color "#8080ff" --label_type relative --variation_type deletion
python histogram.py --input data_HEK/output/KO_sgA_R1_sense_noDSB --output plot_HEK/histogram/KO_sgA_R1_sense_noDSB_insertion.png --color "#ffa500" --label_type relative --variation_type insertion
python histogram.py --input data_HEK/output/KO_sgA_R1_sense_noDSB --output plot_HEK/histogram/KO_sgA_R1_sense_noDSB_substitution.png --color "#bfbfbf" --label_type relative --variation_type substitution
python histogram.py --input data_HEK/output/KO_sgA_R1_sense --output plot_HEK/histogram/KO_sgA_R1_sense_substitution.png --color "#bfbfbf" --label_type relative --variation_type substitution
python histogram.py --input data_HEK/output/KO_sgB_R2_branch_30bpDown --output plot_HEK/histogram/KO_sgB_R2_branch_30bpDown_deletion.png --color "#8080ff" --reverse_pos --label_type absolute --variation_type deletion
python histogram.py --input data_HEK/output/KO_sgB_R2_branch_30bpDown --output plot_HEK/histogram/KO_sgB_R2_branch_30bpDown_insertion.png --color "#ffa500" --reverse_pos --label_type absolute --variation_type insertion
python histogram.py --input data_HEK/output/KO_sgB_R2_branch_30bpDown --output plot_HEK/histogram/KO_sgB_R2_branch_30bpDown_substitution.png --color "#bfbfbf" --reverse_pos --label_type absolute --variation_type substitution
python histogram.py --input data_HEK/output/KO_sgB_R2_branch --output plot_HEK/histogram/KO_sgB_R2_branch_deletion.png --color "#8080ff" --reverse_pos --label_type relative --variation_type deletion
python histogram.py --input data_HEK/output/KO_sgB_R2_branch --output plot_HEK/histogram/KO_sgB_R2_branch_insertion.png --color "#ffa500" --reverse_pos --label_type relative --variation_type insertion
python histogram.py --input data_HEK/output/KO_sgB_R2_branch_noDSB --output plot_HEK/histogram/KO_sgB_R2_branch_noDSB_deletion.png --color "#8080ff" --reverse_pos --label_type relative --variation_type deletion
python histogram.py --input data_HEK/output/KO_sgB_R2_branch_noDSB --output plot_HEK/histogram/KO_sgB_R2_branch_noDSB_insertion.png --color "#ffa500" --reverse_pos --label_type relative --variation_type insertion
python histogram.py --input data_HEK/output/KO_sgB_R2_branch_noDSB --output plot_HEK/histogram/KO_sgB_R2_branch_noDSB_substitution.png --color "#bfbfbf" --reverse_pos --label_type relative --variation_type substitution
python histogram.py --input data_HEK/output/KO_sgB_R2_branch --output plot_HEK/histogram/KO_sgB_R2_branch_substitution.png --color "#bfbfbf" --reverse_pos --label_type relative --variation_type substitution
python histogram.py --input data_HEK/output/KO_sgB_R2_cmv_30bpDown --output plot_HEK/histogram/KO_sgB_R2_cmv_30bpDown_deletion.png --color "#8080ff" --reverse_pos --label_type absolute --variation_type deletion
python histogram.py --input data_HEK/output/KO_sgB_R2_cmv_30bpDown --output plot_HEK/histogram/KO_sgB_R2_cmv_30bpDown_insertion.png --color "#ffa500" --reverse_pos --label_type absolute --variation_type insertion
python histogram.py --input data_HEK/output/KO_sgB_R2_cmv_30bpDown --output plot_HEK/histogram/KO_sgB_R2_cmv_30bpDown_substitution.png --color "#bfbfbf" --reverse_pos --label_type absolute --variation_type substitution
python histogram.py --input data_HEK/output/KO_sgB_R2_cmv --output plot_HEK/histogram/KO_sgB_R2_cmv_deletion.png --color "#8080ff" --reverse_pos --label_type relative --variation_type deletion
python histogram.py --input data_HEK/output/KO_sgB_R2_cmv --output plot_HEK/histogram/KO_sgB_R2_cmv_insertion.png --color "#ffa500" --reverse_pos --label_type relative --variation_type insertion
python histogram.py --input data_HEK/output/KO_sgB_R2_cmv_noDSB --output plot_HEK/histogram/KO_sgB_R2_cmv_noDSB_deletion.png --color "#8080ff" --reverse_pos --label_type relative --variation_type deletion
python histogram.py --input data_HEK/output/KO_sgB_R2_cmv_noDSB --output plot_HEK/histogram/KO_sgB_R2_cmv_noDSB_insertion.png --color "#ffa500" --reverse_pos --label_type relative --variation_type insertion
python histogram.py --input data_HEK/output/KO_sgB_R2_cmv_noDSB --output plot_HEK/histogram/KO_sgB_R2_cmv_noDSB_substitution.png --color "#bfbfbf" --reverse_pos --label_type relative --variation_type substitution
python histogram.py --input data_HEK/output/KO_sgB_R2_cmv --output plot_HEK/histogram/KO_sgB_R2_cmv_substitution.png --color "#bfbfbf" --reverse_pos --label_type relative --variation_type substitution
python histogram.py --input data_HEK/output/KO_sgB_R2_sense_30bpDown --output plot_HEK/histogram/KO_sgB_R2_sense_30bpDown_deletion.png --color "#8080ff" --reverse_pos --label_type absolute --variation_type deletion
python histogram.py --input data_HEK/output/KO_sgB_R2_sense_30bpDown --output plot_HEK/histogram/KO_sgB_R2_sense_30bpDown_insertion.png --color "#ffa500" --reverse_pos --label_type absolute --variation_type insertion
python histogram.py --input data_HEK/output/KO_sgB_R2_sense_30bpDown --output plot_HEK/histogram/KO_sgB_R2_sense_30bpDown_substitution.png --color "#bfbfbf" --reverse_pos --label_type absolute --variation_type substitution
python histogram.py --input data_HEK/output/KO_sgB_R2_sense --output plot_HEK/histogram/KO_sgB_R2_sense_deletion.png --color "#8080ff" --reverse_pos --label_type relative --variation_type deletion
python histogram.py --input data_HEK/output/KO_sgB_R2_sense --output plot_HEK/histogram/KO_sgB_R2_sense_insertion.png --color "#ffa500" --reverse_pos --label_type relative --variation_type insertion
python histogram.py --input data_HEK/output/KO_sgB_R2_sense_noDSB --output plot_HEK/histogram/KO_sgB_R2_sense_noDSB_deletion.png --color "#8080ff" --reverse_pos --label_type relative --variation_type deletion
python histogram.py --input data_HEK/output/KO_sgB_R2_sense_noDSB --output plot_HEK/histogram/KO_sgB_R2_sense_noDSB_insertion.png --color "#ffa500" --reverse_pos --label_type relative --variation_type insertion
python histogram.py --input data_HEK/output/KO_sgB_R2_sense_noDSB --output plot_HEK/histogram/KO_sgB_R2_sense_noDSB_substitution.png --color "#bfbfbf" --reverse_pos --label_type relative --variation_type substitution
python histogram.py --input data_HEK/output/KO_sgB_R2_sense --output plot_HEK/histogram/KO_sgB_R2_sense_substitution.png --color "#bfbfbf" --reverse_pos --label_type relative --variation_type substitution
python histogram.py --input data_HEK/output/WT_sgAB_R1_branch --output plot_HEK/histogram/WT_sgAB_R1_branch_deletion.png --color "#8080ff" --label_type relative --variation_type deletion
python histogram.py --input data_HEK/output/WT_sgAB_R1_branch --output plot_HEK/histogram/WT_sgAB_R1_branch_insertion.png --color "#ffa500" --label_type relative --variation_type insertion
python histogram.py --input data_HEK/output/WT_sgAB_R1_branch --output plot_HEK/histogram/WT_sgAB_R1_branch_substitution.png --color "#bfbfbf" --label_type relative --variation_type substitution
python histogram.py --input data_HEK/output/WT_sgAB_R1_cmv --output plot_HEK/histogram/WT_sgAB_R1_cmv_deletion.png --color "#8080ff" --label_type relative --variation_type deletion
python histogram.py --input data_HEK/output/WT_sgAB_R1_cmv --output plot_HEK/histogram/WT_sgAB_R1_cmv_insertion.png --color "#ffa500" --label_type relative --variation_type insertion
python histogram.py --input data_HEK/output/WT_sgAB_R1_cmv --output plot_HEK/histogram/WT_sgAB_R1_cmv_substitution.png --color "#bfbfbf" --label_type relative --variation_type substitution
python histogram.py --input data_HEK/output/WT_sgAB_R1_sense --output plot_HEK/histogram/WT_sgAB_R1_sense_deletion.png --color "#8080ff" --label_type relative --variation_type deletion
python histogram.py --input data_HEK/output/WT_sgAB_R1_sense --output plot_HEK/histogram/WT_sgAB_R1_sense_insertion.png --color "#ffa500" --label_type relative --variation_type insertion
python histogram.py --input data_HEK/output/WT_sgAB_R1_sense --output plot_HEK/histogram/WT_sgAB_R1_sense_substitution.png --color "#bfbfbf" --label_type relative --variation_type substitution
python histogram.py --input data_HEK/output/WT_sgAB_R2_branch --output plot_HEK/histogram/WT_sgAB_R2_branch_deletion.png --color "#8080ff" --reverse_pos --label_type relative --variation_type deletion
python histogram.py --input data_HEK/output/WT_sgAB_R2_branch --output plot_HEK/histogram/WT_sgAB_R2_branch_insertion.png --color "#ffa500" --reverse_pos --label_type relative --variation_type insertion
python histogram.py --input data_HEK/output/WT_sgAB_R2_branch --output plot_HEK/histogram/WT_sgAB_R2_branch_substitution.png --color "#bfbfbf" --reverse_pos --label_type relative --variation_type substitution
python histogram.py --input data_HEK/output/WT_sgAB_R2_cmv --output plot_HEK/histogram/WT_sgAB_R2_cmv_deletion.png --color "#8080ff" --reverse_pos --label_type relative --variation_type deletion
python histogram.py --input data_HEK/output/WT_sgAB_R2_cmv --output plot_HEK/histogram/WT_sgAB_R2_cmv_insertion.png --color "#ffa500" --reverse_pos --label_type relative --variation_type insertion
python histogram.py --input data_HEK/output/WT_sgAB_R2_cmv --output plot_HEK/histogram/WT_sgAB_R2_cmv_substitution.png --color "#bfbfbf" --reverse_pos --label_type relative --variation_type substitution
python histogram.py --input data_HEK/output/WT_sgAB_R2_sense --output plot_HEK/histogram/WT_sgAB_R2_sense_deletion.png --color "#8080ff" --reverse_pos --label_type relative --variation_type deletion
python histogram.py --input data_HEK/output/WT_sgAB_R2_sense --output plot_HEK/histogram/WT_sgAB_R2_sense_insertion.png --color "#ffa500" --reverse_pos --label_type relative --variation_type insertion
python histogram.py --input data_HEK/output/WT_sgAB_R2_sense --output plot_HEK/histogram/WT_sgAB_R2_sense_substitution.png --color "#bfbfbf" --reverse_pos --label_type relative --variation_type substitution
python histogram.py --input data_HEK/output/WT_sgA_R1_branch_30bpDown --output plot_HEK/histogram/WT_sgA_R1_branch_30bpDown_deletion.png --color "#8080ff" --label_type absolute --variation_type deletion
python histogram.py --input data_HEK/output/WT_sgA_R1_branch_30bpDown --output plot_HEK/histogram/WT_sgA_R1_branch_30bpDown_insertion.png --color "#ffa500" --label_type absolute --variation_type insertion
python histogram.py --input data_HEK/output/WT_sgA_R1_branch_30bpDown --output plot_HEK/histogram/WT_sgA_R1_branch_30bpDown_substitution.png --color "#bfbfbf" --label_type absolute --variation_type substitution
python histogram.py --input data_HEK/output/WT_sgA_R1_branch --output plot_HEK/histogram/WT_sgA_R1_branch_deletion.png --color "#8080ff" --label_type relative --variation_type deletion
python histogram.py --input data_HEK/output/WT_sgA_R1_branch --output plot_HEK/histogram/WT_sgA_R1_branch_insertion.png --color "#ffa500" --label_type relative --variation_type insertion
python histogram.py --input data_HEK/output/WT_sgA_R1_branch_noDSB --output plot_HEK/histogram/WT_sgA_R1_branch_noDSB_deletion.png --color "#8080ff" --label_type relative --variation_type deletion
python histogram.py --input data_HEK/output/WT_sgA_R1_branch_noDSB --output plot_HEK/histogram/WT_sgA_R1_branch_noDSB_insertion.png --color "#ffa500" --label_type relative --variation_type insertion
python histogram.py --input data_HEK/output/WT_sgA_R1_branch_noDSB --output plot_HEK/histogram/WT_sgA_R1_branch_noDSB_substitution.png --color "#bfbfbf" --label_type relative --variation_type substitution
python histogram.py --input data_HEK/output/WT_sgA_R1_branch --output plot_HEK/histogram/WT_sgA_R1_branch_substitution.png --color "#bfbfbf" --label_type relative --variation_type substitution
python histogram.py --input data_HEK/output/WT_sgA_R1_cmv_30bpDown --output plot_HEK/histogram/WT_sgA_R1_cmv_30bpDown_deletion.png --color "#8080ff" --label_type absolute --variation_type deletion
python histogram.py --input data_HEK/output/WT_sgA_R1_cmv_30bpDown --output plot_HEK/histogram/WT_sgA_R1_cmv_30bpDown_insertion.png --color "#ffa500" --label_type absolute --variation_type insertion
python histogram.py --input data_HEK/output/WT_sgA_R1_cmv_30bpDown --output plot_HEK/histogram/WT_sgA_R1_cmv_30bpDown_substitution.png --color "#bfbfbf" --label_type absolute --variation_type substitution
python histogram.py --input data_HEK/output/WT_sgA_R1_cmv --output plot_HEK/histogram/WT_sgA_R1_cmv_deletion.png --color "#8080ff" --label_type relative --variation_type deletion
python histogram.py --input data_HEK/output/WT_sgA_R1_cmv --output plot_HEK/histogram/WT_sgA_R1_cmv_insertion.png --color "#ffa500" --label_type relative --variation_type insertion
python histogram.py --input data_HEK/output/WT_sgA_R1_cmv_noDSB --output plot_HEK/histogram/WT_sgA_R1_cmv_noDSB_deletion.png --color "#8080ff" --label_type relative --variation_type deletion
python histogram.py --input data_HEK/output/WT_sgA_R1_cmv_noDSB --output plot_HEK/histogram/WT_sgA_R1_cmv_noDSB_insertion.png --color "#ffa500" --label_type relative --variation_type insertion
python histogram.py --input data_HEK/output/WT_sgA_R1_cmv_noDSB --output plot_HEK/histogram/WT_sgA_R1_cmv_noDSB_substitution.png --color "#bfbfbf" --label_type relative --variation_type substitution
python histogram.py --input data_HEK/output/WT_sgA_R1_cmv --output plot_HEK/histogram/WT_sgA_R1_cmv_substitution.png --color "#bfbfbf" --label_type relative --variation_type substitution
python histogram.py --input data_HEK/output/WT_sgA_R1_sense_30bpDown --output plot_HEK/histogram/WT_sgA_R1_sense_30bpDown_deletion.png --color "#8080ff" --label_type absolute --variation_type deletion
python histogram.py --input data_HEK/output/WT_sgA_R1_sense_30bpDown --output plot_HEK/histogram/WT_sgA_R1_sense_30bpDown_insertion.png --color "#ffa500" --label_type absolute --variation_type insertion
python histogram.py --input data_HEK/output/WT_sgA_R1_sense_30bpDown --output plot_HEK/histogram/WT_sgA_R1_sense_30bpDown_substitution.png --color "#bfbfbf" --label_type absolute --variation_type substitution
python histogram.py --input data_HEK/output/WT_sgA_R1_sense --output plot_HEK/histogram/WT_sgA_R1_sense_deletion.png --color "#8080ff" --label_type relative --variation_type deletion
python histogram.py --input data_HEK/output/WT_sgA_R1_sense --output plot_HEK/histogram/WT_sgA_R1_sense_insertion.png --color "#ffa500" --label_type relative --variation_type insertion
python histogram.py --input data_HEK/output/WT_sgA_R1_sense_noDSB --output plot_HEK/histogram/WT_sgA_R1_sense_noDSB_deletion.png --color "#8080ff" --label_type relative --variation_type deletion
python histogram.py --input data_HEK/output/WT_sgA_R1_sense_noDSB --output plot_HEK/histogram/WT_sgA_R1_sense_noDSB_insertion.png --color "#ffa500" --label_type relative --variation_type insertion
python histogram.py --input data_HEK/output/WT_sgA_R1_sense_noDSB --output plot_HEK/histogram/WT_sgA_R1_sense_noDSB_substitution.png --color "#bfbfbf" --label_type relative --variation_type substitution
python histogram.py --input data_HEK/output/WT_sgA_R1_sense --output plot_HEK/histogram/WT_sgA_R1_sense_substitution.png --color "#bfbfbf" --label_type relative --variation_type substitution
python histogram.py --input data_HEK/output/WT_sgB_R2_branch_30bpDown --output plot_HEK/histogram/WT_sgB_R2_branch_30bpDown_deletion.png --color "#8080ff" --reverse_pos --label_type absolute --variation_type deletion
python histogram.py --input data_HEK/output/WT_sgB_R2_branch_30bpDown --output plot_HEK/histogram/WT_sgB_R2_branch_30bpDown_insertion.png --color "#ffa500" --reverse_pos --label_type absolute --variation_type insertion
python histogram.py --input data_HEK/output/WT_sgB_R2_branch_30bpDown --output plot_HEK/histogram/WT_sgB_R2_branch_30bpDown_substitution.png --color "#bfbfbf" --reverse_pos --label_type absolute --variation_type substitution
python histogram.py --input data_HEK/output/WT_sgB_R2_branch --output plot_HEK/histogram/WT_sgB_R2_branch_deletion.png --color "#8080ff" --reverse_pos --label_type relative --variation_type deletion
python histogram.py --input data_HEK/output/WT_sgB_R2_branch --output plot_HEK/histogram/WT_sgB_R2_branch_insertion.png --color "#ffa500" --reverse_pos --label_type relative --variation_type insertion
python histogram.py --input data_HEK/output/WT_sgB_R2_branch_noDSB --output plot_HEK/histogram/WT_sgB_R2_branch_noDSB_deletion.png --color "#8080ff" --reverse_pos --label_type relative --variation_type deletion
python histogram.py --input data_HEK/output/WT_sgB_R2_branch_noDSB --output plot_HEK/histogram/WT_sgB_R2_branch_noDSB_insertion.png --color "#ffa500" --reverse_pos --label_type relative --variation_type insertion
python histogram.py --input data_HEK/output/WT_sgB_R2_branch_noDSB --output plot_HEK/histogram/WT_sgB_R2_branch_noDSB_substitution.png --color "#bfbfbf" --reverse_pos --label_type relative --variation_type substitution
python histogram.py --input data_HEK/output/WT_sgB_R2_branch --output plot_HEK/histogram/WT_sgB_R2_branch_substitution.png --color "#bfbfbf" --reverse_pos --label_type relative --variation_type substitution
python histogram.py --input data_HEK/output/WT_sgB_R2_cmv_30bpDown --output plot_HEK/histogram/WT_sgB_R2_cmv_30bpDown_deletion.png --color "#8080ff" --reverse_pos --label_type absolute --variation_type deletion
python histogram.py --input data_HEK/output/WT_sgB_R2_cmv_30bpDown --output plot_HEK/histogram/WT_sgB_R2_cmv_30bpDown_insertion.png --color "#ffa500" --reverse_pos --label_type absolute --variation_type insertion
python histogram.py --input data_HEK/output/WT_sgB_R2_cmv_30bpDown --output plot_HEK/histogram/WT_sgB_R2_cmv_30bpDown_substitution.png --color "#bfbfbf" --reverse_pos --label_type absolute --variation_type substitution
python histogram.py --input data_HEK/output/WT_sgB_R2_cmv --output plot_HEK/histogram/WT_sgB_R2_cmv_deletion.png --color "#8080ff" --reverse_pos --label_type relative --variation_type deletion
python histogram.py --input data_HEK/output/WT_sgB_R2_cmv --output plot_HEK/histogram/WT_sgB_R2_cmv_insertion.png --color "#ffa500" --reverse_pos --label_type relative --variation_type insertion
python histogram.py --input data_HEK/output/WT_sgB_R2_cmv_noDSB --output plot_HEK/histogram/WT_sgB_R2_cmv_noDSB_deletion.png --color "#8080ff" --reverse_pos --label_type relative --variation_type deletion
python histogram.py --input data_HEK/output/WT_sgB_R2_cmv_noDSB --output plot_HEK/histogram/WT_sgB_R2_cmv_noDSB_insertion.png --color "#ffa500" --reverse_pos --label_type relative --variation_type insertion
python histogram.py --input data_HEK/output/WT_sgB_R2_cmv_noDSB --output plot_HEK/histogram/WT_sgB_R2_cmv_noDSB_substitution.png --color "#bfbfbf" --reverse_pos --label_type relative --variation_type substitution
python histogram.py --input data_HEK/output/WT_sgB_R2_cmv --output plot_HEK/histogram/WT_sgB_R2_cmv_substitution.png --color "#bfbfbf" --reverse_pos --label_type relative --variation_type substitution
python histogram.py --input data_HEK/output/WT_sgB_R2_sense_30bpDown --output plot_HEK/histogram/WT_sgB_R2_sense_30bpDown_deletion.png --color "#8080ff" --reverse_pos --label_type absolute --variation_type deletion
python histogram.py --input data_HEK/output/WT_sgB_R2_sense_30bpDown --output plot_HEK/histogram/WT_sgB_R2_sense_30bpDown_insertion.png --color "#ffa500" --reverse_pos --label_type absolute --variation_type insertion
python histogram.py --input data_HEK/output/WT_sgB_R2_sense_30bpDown --output plot_HEK/histogram/WT_sgB_R2_sense_30bpDown_substitution.png --color "#bfbfbf" --reverse_pos --label_type absolute --variation_type substitution
python histogram.py --input data_HEK/output/WT_sgB_R2_sense --output plot_HEK/histogram/WT_sgB_R2_sense_deletion.png --color "#8080ff" --reverse_pos --label_type relative --variation_type deletion
python histogram.py --input data_HEK/output/WT_sgB_R2_sense --output plot_HEK/histogram/WT_sgB_R2_sense_insertion.png --color "#ffa500" --reverse_pos --label_type relative --variation_type insertion
python histogram.py --input data_HEK/output/WT_sgB_R2_sense_noDSB --output plot_HEK/histogram/WT_sgB_R2_sense_noDSB_deletion.png --color "#8080ff" --reverse_pos --label_type relative --variation_type deletion
python histogram.py --input data_HEK/output/WT_sgB_R2_sense_noDSB --output plot_HEK/histogram/WT_sgB_R2_sense_noDSB_insertion.png --color "#ffa500" --reverse_pos --label_type relative --variation_type insertion
python histogram.py --input data_HEK/output/WT_sgB_R2_sense_noDSB --output plot_HEK/histogram/WT_sgB_R2_sense_noDSB_substitution.png --color "#bfbfbf" --reverse_pos --label_type relative --variation_type substitution
python histogram.py --input data_HEK/output/WT_sgB_R2_sense --output plot_HEK/histogram/WT_sgB_R2_sense_substitution.png --color "#bfbfbf" --reverse_pos --label_type relative --variation_type substitution
python histogram.py --input data_HEK/output/WT_sgCD_R1_antisense_new --output plot_HEK/histogram/WT_sgCD_R1_antisense_new_deletion.png --color "#8080ff" --label_type relative --variation_type deletion
python histogram.py --input data_HEK/output/WT_sgCD_R1_antisense_new --output plot_HEK/histogram/WT_sgCD_R1_antisense_new_insertion.png --color "#ffa500" --label_type relative --variation_type insertion
python histogram.py --input data_HEK/output/WT_sgCD_R1_antisense_new --output plot_HEK/histogram/WT_sgCD_R1_antisense_new_substitution.png --color "#bfbfbf" --label_type relative --variation_type substitution
python histogram.py --input data_HEK/output/WT_sgCD_R1_antisense_old --output plot_HEK/histogram/WT_sgCD_R1_antisense_old_deletion.png --color "#8080ff" --label_type relative --variation_type deletion
python histogram.py --input data_HEK/output/WT_sgCD_R1_antisense_old --output plot_HEK/histogram/WT_sgCD_R1_antisense_old_insertion.png --color "#ffa500" --label_type relative --variation_type insertion
python histogram.py --input data_HEK/output/WT_sgCD_R1_antisense_old --output plot_HEK/histogram/WT_sgCD_R1_antisense_old_substitution.png --color "#bfbfbf" --label_type relative --variation_type substitution
python histogram.py --input data_HEK/output/WT_sgCD_R1_splicing_new --output plot_HEK/histogram/WT_sgCD_R1_splicing_new_deletion.png --color "#8080ff" --label_type relative --variation_type deletion
python histogram.py --input data_HEK/output/WT_sgCD_R1_splicing_new --output plot_HEK/histogram/WT_sgCD_R1_splicing_new_insertion.png --color "#ffa500" --label_type relative --variation_type insertion
python histogram.py --input data_HEK/output/WT_sgCD_R1_splicing_new --output plot_HEK/histogram/WT_sgCD_R1_splicing_new_substitution.png --color "#bfbfbf" --label_type relative --variation_type substitution
python histogram.py --input data_HEK/output/WT_sgCD_R1_splicing_old --output plot_HEK/histogram/WT_sgCD_R1_splicing_old_deletion.png --color "#8080ff" --label_type relative --variation_type deletion
python histogram.py --input data_HEK/output/WT_sgCD_R1_splicing_old --output plot_HEK/histogram/WT_sgCD_R1_splicing_old_insertion.png --color "#ffa500" --label_type relative --variation_type insertion
python histogram.py --input data_HEK/output/WT_sgCD_R1_splicing_old --output plot_HEK/histogram/WT_sgCD_R1_splicing_old_substitution.png --color "#bfbfbf" --label_type relative --variation_type substitution
python histogram.py --input data_HEK/output/WT_sgCD_R2_antisense_new --output plot_HEK/histogram/WT_sgCD_R2_antisense_new_deletion.png --color "#8080ff" --reverse_pos --label_type relative --variation_type deletion
python histogram.py --input data_HEK/output/WT_sgCD_R2_antisense_new --output plot_HEK/histogram/WT_sgCD_R2_antisense_new_insertion.png --color "#ffa500" --reverse_pos --label_type relative --variation_type insertion
python histogram.py --input data_HEK/output/WT_sgCD_R2_antisense_new --output plot_HEK/histogram/WT_sgCD_R2_antisense_new_substitution.png --color "#bfbfbf" --reverse_pos --label_type relative --variation_type substitution
python histogram.py --input data_HEK/output/WT_sgCD_R2_antisense_old --output plot_HEK/histogram/WT_sgCD_R2_antisense_old_deletion.png --color "#8080ff" --reverse_pos --label_type relative --variation_type deletion
python histogram.py --input data_HEK/output/WT_sgCD_R2_antisense_old --output plot_HEK/histogram/WT_sgCD_R2_antisense_old_insertion.png --color "#ffa500" --reverse_pos --label_type relative --variation_type insertion
python histogram.py --input data_HEK/output/WT_sgCD_R2_antisense_old --output plot_HEK/histogram/WT_sgCD_R2_antisense_old_substitution.png --color "#bfbfbf" --reverse_pos --label_type relative --variation_type substitution
python histogram.py --input data_HEK/output/WT_sgCD_R2_splicing_new --output plot_HEK/histogram/WT_sgCD_R2_splicing_new_deletion.png --color "#8080ff" --reverse_pos --label_type relative --variation_type deletion
python histogram.py --input data_HEK/output/WT_sgCD_R2_splicing_new --output plot_HEK/histogram/WT_sgCD_R2_splicing_new_insertion.png --color "#ffa500" --reverse_pos --label_type relative --variation_type insertion
python histogram.py --input data_HEK/output/WT_sgCD_R2_splicing_new --output plot_HEK/histogram/WT_sgCD_R2_splicing_new_substitution.png --color "#bfbfbf" --reverse_pos --label_type relative --variation_type substitution
python histogram.py --input data_HEK/output/WT_sgCD_R2_splicing_old --output plot_HEK/histogram/WT_sgCD_R2_splicing_old_deletion.png --color "#8080ff" --reverse_pos --label_type relative --variation_type deletion
python histogram.py --input data_HEK/output/WT_sgCD_R2_splicing_old --output plot_HEK/histogram/WT_sgCD_R2_splicing_old_insertion.png --color "#ffa500" --reverse_pos --label_type relative --variation_type insertion
python histogram.py --input data_HEK/output/WT_sgCD_R2_splicing_old --output plot_HEK/histogram/WT_sgCD_R2_splicing_old_substitution.png --color "#bfbfbf" --reverse_pos --label_type relative --variation_type substitution
